import FWCore.ParameterSet.Config as cms

maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )
readFiles = cms.untracked.vstring()
secFiles = cms.untracked.vstring() 
source = cms.Source ("PoolSource",fileNames = readFiles, secondaryFileNames = secFiles, skipEvents = cms.untracked.uint32(0))

readFiles.extend( [
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_0.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_100.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_101.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_102.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_103.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_104.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_105.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_106.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_107.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_108.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_109.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_10.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_110.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_111.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_112.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_113.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_114.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_115.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_116.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_117.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_118.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_119.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_11.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_120.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_121.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_122.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_123.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_124.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_125.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_126.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_127.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_128.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_129.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_12.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_130.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_131.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_132.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_133.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_134.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_135.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_136.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_137.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_138.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_139.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_13.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_140.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_141.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_142.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_143.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_144.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_145.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_146.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_147.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_148.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_149.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_14.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_150.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_151.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_152.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_153.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_154.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_155.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_156.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_157.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_158.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_159.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_15.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_160.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_161.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_162.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_163.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_164.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_165.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_166.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_167.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_168.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_169.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_16.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_170.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_171.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_172.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_173.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_174.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_175.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_176.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_177.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_178.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_179.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_17.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_180.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_181.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_182.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_183.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_184.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_185.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_186.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_187.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_188.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_189.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_18.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_190.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_191.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_192.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_193.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_194.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_195.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_196.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_197.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_198.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_199.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_19.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_1.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_200.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_201.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_202.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_203.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_204.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_205.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_206.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_207.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_208.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_209.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_20.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_210.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_211.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_212.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_213.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_214.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_215.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_216.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_217.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_218.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_219.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_21.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_220.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_221.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_222.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_223.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_224.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_225.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_226.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_227.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_228.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_229.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_22.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_230.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_231.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_232.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_233.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_234.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_235.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_236.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_237.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_238.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_239.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_23.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_240.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_241.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_242.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_243.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_244.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_245.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_246.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_247.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_248.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_249.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_24.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_250.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_251.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_252.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_253.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_254.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_255.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_256.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_257.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_258.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_259.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_25.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_260.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_261.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_262.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_263.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_264.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_265.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_266.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_267.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_268.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_269.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_26.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_270.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_271.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_272.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_273.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_274.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_275.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_276.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_277.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_278.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_279.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_27.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_280.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_281.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_282.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_283.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_284.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_285.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_286.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_287.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_288.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_289.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_28.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_290.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_291.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_292.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_293.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_294.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_295.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_296.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_297.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_298.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_299.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_29.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_2.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_300.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_301.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_302.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_303.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_304.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_305.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_306.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_307.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_308.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_309.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_30.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_310.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_311.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_312.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_313.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_314.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_315.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_316.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_317.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_318.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_319.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_31.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_320.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_321.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_322.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_323.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_324.root' ] )

readFiles.extend( [
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_325.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_326.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_327.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_328.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_329.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_32.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_330.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_331.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_332.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_333.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_334.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_335.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_336.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_337.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_338.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_339.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_33.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_340.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_341.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_342.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_343.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_344.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_345.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_346.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_347.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_348.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_349.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_34.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_350.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_351.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_352.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_353.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_354.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_355.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_356.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_357.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_358.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_359.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_35.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_360.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_361.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_362.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_363.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_364.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_365.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_366.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_367.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_368.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_369.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_36.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_370.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_371.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_372.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_373.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_374.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_375.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_376.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_377.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_378.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_379.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_37.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_380.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_381.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_382.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_383.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_384.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_385.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_386.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_387.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_388.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_389.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_38.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_390.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_391.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_392.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_393.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_394.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_395.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_396.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_397.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_398.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_399.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_39.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_3.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_400.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_401.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_402.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_403.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_404.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_405.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_406.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_407.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_408.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_409.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_40.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_410.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_411.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_412.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_413.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_414.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_415.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_416.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_417.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_418.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_419.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_41.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_420.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_421.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_422.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_423.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_424.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_425.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_426.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_427.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_428.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_429.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_42.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_430.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_431.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_432.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_433.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_434.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_435.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_436.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_437.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_438.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_439.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_43.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_440.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_441.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_442.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_443.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_444.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_445.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_446.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_447.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_448.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_449.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_44.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_450.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_451.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_452.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_453.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_454.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_455.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_456.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_457.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_458.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_459.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_45.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_460.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_461.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_462.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_463.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_464.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_465.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_466.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_467.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_468.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_469.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_46.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_470.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_471.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_472.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_473.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_474.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_475.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_476.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_477.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_478.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_479.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_47.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_480.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_481.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_482.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_483.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_484.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_485.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_486.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_487.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_488.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_489.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_48.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_490.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_491.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_492.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_493.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_494.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_495.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_496.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_497.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_498.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_499.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_49.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_4.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_50.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_51.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_52.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_53.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_54.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_55.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_56.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_57.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_58.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_59.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_5.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_60.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_61.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_62.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_63.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_64.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_65.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_66.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_67.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_68.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_69.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_6.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_70.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_71.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_72.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_73.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_74.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_75.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_76.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_77.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_78.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_79.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_7.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_80.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_81.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_82.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_83.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_84.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_85.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_86.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_87.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_88.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_89.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_8.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_90.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_91.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_92.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_93.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_94.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_95.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_96.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_97.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_98.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_99.root',
       'file:/scratch/hh/dust/naf/cms/user/gosseli/alljets/bbbar_6jets_7TeV_pythia6_GEN/bbbar_6jets_7TeV_pythia6_GEN_9.root'  ] )

secFiles.extend( [
               ] )

process = cms.Process("UserTest")

## configure message logger
process.load("FWCore.MessageLogger.MessageLogger_cfi")
#process.MessageLogger.cerr.threshold = 'INFO'
process.MessageLogger.categories.append('ParticleListDrawer')
process.MessageLogger.cerr.FwkReport.reportEvery = 1000

#-------------------------------------------------
# process configuration
#-------------------------------------------------

## define input
process.source = source

## define maximal number of events to loop over
process.maxEvents = maxEvents

## configure process options
process.options = cms.untracked.PSet(
    wantSummary = cms.untracked.bool(True)
)

## register TFileService
process.TFileService = cms.Service("TFileService",
            fileName = cms.string("convertGenToPatJets_test.root")
)

## analyze PatJets
process.load("TopAnalysis.TopAnalyzer.JetKinematics_cfi")
process.load("TopAnalysis.TopAnalyzer.JetQuality_cfi")

process.kine = process.analyzeJetKinematics.clone(src = "selectedPatJets")
process.qual = process.analyzeJetQuality.clone(src = "selectedPatJets")

## convert GenJets to PatJets
process.load("TopAnalysis.TopUtils.convertGenToPatJets_cff")

## debug modules
process.load("TopQuarkAnalysis.TopEventProducers.sequences.printGenParticles_cff")

process.printTree = cms.EDAnalyzer("ParticleTreeDrawer",
    src = cms.InputTag("genParticles"),
    printP4 = cms.untracked.bool(False),
    printPtEtaPhi = cms.untracked.bool(False),
    printVertex = cms.untracked.bool(False),
    printStatus = cms.untracked.bool(False),
    printIndex  = cms.untracked.bool(False)
)

process.dump = cms.EDAnalyzer("EventContentAnalyzer")

## process everything
process.p = cms.Path(process.fullHadGenJetSelection *
                     process.convertGenToPatJets *
                     process.kine *
                     process.qual
                     #process.printGenParticles
                     #process.printTree
                     )
