# QCD
cp naf_Elqcd*1/elec*Fall11PF.root WGspace/RecentAnalysisRun/MergedFiles
cp naf_Elqcd*2/elec*Fall11PF.root WGspace/RecentAnalysisRun/MergedFiles
cp naf_Elqcd*3/elec*Fall11PF.root WGspace/RecentAnalysisRun/MergedFiles
cp naf_Muqcd/muonDiffXSec*PF.root WGspace/RecentAnalysisRun
cp naf_Elqcd*1/elec*Fall11PF.txt WGspace/RecentAnalysisRun/TriggerReports
cp naf_Elqcd*2/elec*Fall11PF.txt WGspace/RecentAnalysisRun/TriggerReports
cp naf_Elqcd*3/elec*Fall11PF.txt WGspace/RecentAnalysisRun/TriggerReports
cp naf_Muqcd/muonDiffXSec*PF.txt WGspace/RecentAnalysisRun/TriggerReports
# QCD JES
cp naf_Elqcd*1JESUp/elec*Fall11PF.root WGspace/RecentAnalysisRun/JESUp/MergedFiles
cp naf_Elqcd*2JESUp/elec*Fall11PF.root WGspace/RecentAnalysisRun/JESUp/MergedFiles
cp naf_Elqcd*3JESUp/elec*Fall11PF.root WGspace/RecentAnalysisRun/JESUp/MergedFiles
cp naf_MuqcdJESUp/muonDiffXSec*PF.root WGspace/RecentAnalysisRun/JESUp
cp naf_Elqcd*1JESUp/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JESUp/TriggerReports
cp naf_Elqcd*2JESUp/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JESUp/TriggerReports
cp naf_Elqcd*3JESUp/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JESUp/TriggerReports
cp naf_MuqcdJESUp/muonDiffXSec*PF.txt WGspace/RecentAnalysisRun/JESUp/TriggerReports
cp naf_Elqcd*1JESDn/elec*Fall11PF.root WGspace/RecentAnalysisRun/JESDown/MergedFiles
cp naf_Elqcd*2JESDn/elec*Fall11PF.root WGspace/RecentAnalysisRun/JESDown/MergedFiles
cp naf_Elqcd*3JESDn/elec*Fall11PF.root WGspace/RecentAnalysisRun/JESDown/MergedFiles
cp naf_MuqcdJESDn/muonDiffXSec*PF.root WGspace/RecentAnalysisRun/JESDown
cp naf_Elqcd*1JESDn/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JESDown/TriggerReports
cp naf_Elqcd*2JESDn/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JESDown/TriggerReports
cp naf_Elqcd*3JESDn/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JESDown/TriggerReports
cp naf_MuqcdJESDn/muonDiffXSec*PF.txt WGspace/RecentAnalysisRun/JESDown/TriggerReports
# QCD JER
cp naf_Elqcd*1JERUp/elec*Fall11PF.root WGspace/RecentAnalysisRun/JERUp/MergedFiles
cp naf_Elqcd*2JERUp/elec*Fall11PF.root WGspace/RecentAnalysisRun/JERUp/MergedFiles
cp naf_Elqcd*3JERUp/elec*Fall11PF.root WGspace/RecentAnalysisRun/JERUp/MergedFiles
cp naf_MuqcdJERUp/muonDiffXSec*PF.root WGspace/RecentAnalysisRun/JERUp
cp naf_Elqcd*1JERUp/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JERUp/TriggerReports
cp naf_Elqcd*2JERUp/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JERUp/TriggerReports
cp naf_Elqcd*3JERUp/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JERUp/TriggerReports
cp naf_MuqcdJERUp/muonDiffXSec*PF.txt WGspace/RecentAnalysisRun/JERUp/TriggerReports
cp naf_Elqcd*1JERDn/elec*Fall11PF.root WGspace/RecentAnalysisRun/JERDown/MergedFiles
cp naf_Elqcd*2JERDn/elec*Fall11PF.root WGspace/RecentAnalysisRun/JERDown/MergedFiles
cp naf_Elqcd*3JERDn/elec*Fall11PF.root WGspace/RecentAnalysisRun/JERDown/MergedFiles
cp naf_MuqcdJERDn/muonDiffXSec*PF.root WGspace/RecentAnalysisRun/JERDown
cp naf_Elqcd*1JERDn/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JERDown/TriggerReports
cp naf_Elqcd*2JERDn/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JERDown/TriggerReports
cp naf_Elqcd*3JERDn/elec*Fall11PF.txt WGspace/RecentAnalysisRun/JERDown/TriggerReports
cp naf_MuqcdJERDn/muonDiffXSec*PF.txt WGspace/RecentAnalysisRun/JERDown/TriggerReports
# Z+jets
cp naf_*zjets/*PF.root WGspace/RecentAnalysisRun/
cp naf_*zjets/*PF.txt WGspace/RecentAnalysisRun/TriggerReports
cp naf_*zjetsJESUp/*PF.root WGspace/RecentAnalysisRun/JESUp
cp naf_*zjetsJESUp/*PF.txt WGspace/RecentAnalysisRun/JESUp/TriggerReports
cp naf_*zjetsJESDn/*PF.root WGspace/RecentAnalysisRun/JESDown
cp naf_*zjetsJESDn/*PF.txt WGspace/RecentAnalysisRun/JESDown/TriggerReports
cp naf_*zjetsJERUp/*PF.root WGspace/RecentAnalysisRun/JERUp
cp naf_*zjetsJERUp/*PF.txt WGspace/RecentAnalysisRun/JERUp/TriggerReports
cp naf_*zjetsJERDn/*PF.root WGspace/RecentAnalysisRun/JERDown
cp naf_*zjetsJERDn/*PF.txt WGspace/RecentAnalysisRun/JERDown/TriggerReports
cp naf_*zjetsMatchUp/*PF.root WGspace/RecentAnalysisRun/MatchUp
cp naf_*zjetsMatchUp/*PF.txt WGspace/RecentAnalysisRun/MatchUp/TriggerReports
cp naf_*zjetsMatchDn/*PF.root WGspace/RecentAnalysisRun/MatchDown
cp naf_*zjetsMatchDn/*PF.txt WGspace/RecentAnalysisRun/MatchDown/TriggerReports
cp naf_*zjetsScaleUp/*PF.root WGspace/RecentAnalysisRun/ScaleUp
cp naf_*zjetsScaleUp/*PF.txt WGspace/RecentAnalysisRun/ScaleUp/TriggerReports
cp naf_*zjetsScaleDn/*PF.root WGspace/RecentAnalysisRun/ScaleDown
cp naf_*zjetsScaleDn/*PF.txt WGspace/RecentAnalysisRun/ScaleDown/TriggerReports
