#!/bin/sh

if [ $# -lt 2 ]
    then
    echo 'Usage:'
    echo './jobSubmit <JobName> <ConfigFile> <OptionalParametersForCMSRUN>'
else
    currentPath=`pwd`
    cfgFile=""
    for i in $@
      do
      if [ $i != $1 ]
	  then
	  cfgFile=$cfgFile$i" "
      fi
    done
    #inter1=${cfgFile//\//\\\/}
    #configFile=${inter1/\ /\\\ }
    configFile=$cfgFile

    mkdir $1
    cd $1

    #sed s/VAR_JOB_NAME/$1/g <../scriptToSubmit|sed s/VAR_CURRENT_PATH/${currentPath//\//\\\/}/g |sed s/VAR_CONFIG_FILE/"$configFile"/g >$1'.sh'
    echo '#!/bin/sh'                                                                                                   >$1'.sh'
    echo '#'													     >>$1'.sh'
    echo '#(make sure the right shell will be used)'			        				     >>$1'.sh'
    echo '#$ -S /bin/sh'											     >>$1'.sh'
    echo '#'	        											     >>$1'.sh'
    echo '#(inherit the current shell environment to the job)'							     >>$1'.sh'
    echo '#$ -V'												     >>$1'.sh'
    echo '#'													     >>$1'.sh'
    echo '#(the cpu time for this job) 0:14:59 OR 0:59:59 OR 11:59:59 OR 47:59:59 OR 167:59:59'			     >>$1'.sh'
    echo '#$ -l h_cpu=11:59:59'											     >>$1'.sh'
    echo '#'													     >>$1'.sh'
    echo '#(the maximum memory usage of this job)'								     >>$1'.sh'
    echo '#$ -l h_vmem=2G'											     >>$1'.sh'
    echo '#'													     >>$1'.sh'
    echo '#(stderr and stdout are merged together to stdout)'							     >>$1'.sh'
    echo '#$ -j y'												     >>$1'.sh'
    echo '#'													     >>$1'.sh'
    echo '#(stderr and stdout are merged together to stdout)'							     >>$1'.sh'
    echo '#$ -o '$currentPath'/'$1'/'$1'.stdout'         				                	     >>$1'.sh'
    echo '#'													     >>$1'.sh'
    echo "#(send mail on job's end and abort)"									     >>$1'.sh'
    echo '#$ -m ae'												     >>$1'.sh'
    echo '#'													     >>$1'.sh'
    echo '#(specifies the job name)'										     >>$1'.sh'
    echo '#$ -N '$1							         				     >>$1'.sh'
    echo ' '													     >>$1'.sh'
    echo '# change to working directory'									     >>$1'.sh'
    echo 'cd '$currentPath'/'$1	                		                				     >>$1'.sh'
    echo '# write calculated output to scratch first (is configured in the configuration file)'			     >>$1'.sh'
    echo 'cmsRun '$currentPath'/'$configFile     								     >>$1'.sh'
    echo '# copy the output to dCache'										     >>$1'.sh'
    echo '#dcput /tmp/patTuple_6jets.root /pnfs/desy.de/cms/tier2/store/user/eschliec/Run2010A/patTuple_6jets.root'  >>$1'.sh'

    chmod a+x $1'.sh'

    echo 'Submitting: '$currentPath'/'$1
    qsub $1'.sh'
    
    echo 'Successfully submitted job'

fi
