## ttbar pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=sig" -p ttbar10_nloPAT -s 0 -e 991694 -o analyzeFullHadronicSelection_sig' -n 15 --name sig_nlo_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=bkg" -p ttbar10_nloPAT -s 0 -e 991694 -o analyzeFullHadronicSelection_bkg' -n 10 --name bkg_nlo_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=sig" -p ttbar10_madPAT -s 0 -e 1483404 -o analyzeFullHadronicSelection_sig' -n 20 --name sig_mad_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=bkg" -p ttbar10_madPAT -s 0 -e 1483404 -o analyzeFullHadronicSelection_bkg' -n 16 --name bkg_mad_pf

## qcd pythia pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=30." -p qcd10_pt15_pat -s 0 -e 1086 -o analyzeFullHadronicSelection' -n 1 --name pt0015_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=80." -p qcd10_pt30_pat -s 0 -e 10481 -o analyzeFullHadronicSelection' -n 1 --name pt0030_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=170." -p qcd10_pt80_pat -s 0 -e 100318 -o analyzeFullHadronicSelection' -n 1 --name pt0080_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=300." -p qcd10_pt170_pat -s 0 -e 329132 -o analyzeFullHadronicSelection' -n 4 --name pt0170_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=470." -p qcd10_pt300_pat -s 0 -e 541193 -o analyzeFullHadronicSelection' -n 11 --name pt0300_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=800." -p qcd10_pt470_pat -s 0 -e 430842 -o analyzeFullHadronicSelection' -n 11 --name pt0470_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=1400." -p qcd10_pt800_pat -s 0 -e 462765 -o analyzeFullHadronicSelection' -n 15 --name pt0800_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd" -p qcd10_pt1400_pat -s 0 -e 221277 -o analyzeFullHadronicSelection' -n 15 --name pt1400_pf

## qcd herwig pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=30." -p qcd10_pt15_her_pat -s 0 -e 120 -o analyzeFullHadronicSelection' -n 1 --name pt0015_her_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=80." -p qcd10_pt30_her_pat -s 0 -e 1292 -o analyzeFullHadronicSelection' -n 1 --name pt0030_her_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=170." -p qcd10_pt80_her_pat -s 0 -e 25301 -o analyzeFullHadronicSelection' -n 1 --name pt0080_her_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=300." -p qcd10_pt170_her_pat -s 0 -e 110065 -o analyzeFullHadronicSelection' -n 2 --name pt0170_her_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=470." -p qcd10_pt300_her_pat -s 0 -e 151068 -o analyzeFullHadronicSelection' -n 3 --name pt0300_her_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=800." -p qcd10_pt470_her_pat -s 0 -e 90612 -o analyzeFullHadronicSelection' -n 3 --name pt0470_her_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=1400." -p qcd10_pt800_her_pat -s 0 -e 58869 -o analyzeFullHadronicSelection' -n 3 --name pt0800_her_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd" -p qcd10_pt1400_her_pat -s 0 -e 27288 -o analyzeFullHadronicSelection' -n 3 --name pt1400_her_pf

## qcd madgraph pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=all" -p qcd10_pt100_mad_pat -s 0 -e 46226 -o analyzeFullHadronicSelection' -n 1 --name pt0100_mad_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=all" -p qcd10_pt250_mad_pat -s 0 -e 380278 -o analyzeFullHadronicSelection' -n 10 --name pt0250_mad_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=all" -p qcd10_pt500_mad_pat -s 0 -e 958891 -o analyzeFullHadronicSelection' -n 20 --name pt0500_mad_pf
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=all" -p qcd10_pt1000_mad_pat -s 0 -e 538493 -o analyzeFullHadronicSelection' -n 15 --name pt1000_mad_pf

## ttbar calo
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=sig usePF=0" -p ttbar10_nloPAT -s 0 -e 991694 -o analyzeFullHadronicSelection_sig' -n 15 --name sig_nlo
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=bkg usePF=0" -p ttbar10_nloPAT -s 0 -e 991694 -o analyzeFullHadronicSelection_bkg' -n 10 --name bkg_nlo
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=sig usePF=0" -p ttbar10_madPAT -s 0 -e 1483404 -o analyzeFullHadronicSelection_sig' -n 20 --name sig_mad
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=bkg usePF=0" -p ttbar10_madPAT -s 0 -e 1483404 -o analyzeFullHadronicSelection_bkg' -n 16 --name bkg_mad

## qcd pythia calo
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=30. usePF=0" -p qcd10_pt15_pat -s 0 -e 1086 -o analyzeFullHadronicSelection' -n 1 --name pt0015
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=80. usePF=0" -p qcd10_pt30_pat -s 0 -e 10481 -o analyzeFullHadronicSelection' -n 1 --name pt0030
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=170. usePF=0" -p qcd10_pt80_pat -s 0 -e 100318 -o analyzeFullHadronicSelection' -n 1 --name pt0080
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=300. usePF=0" -p qcd10_pt170_pat -s 0 -e 329132 -o analyzeFullHadronicSelection' -n 4 --name pt0170
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=470. usePF=0" -p qcd10_pt300_pat -s 0 -e 541193 -o analyzeFullHadronicSelection' -n 11 --name pt0300
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=800. usePF=0" -p qcd10_pt470_pat -s 0 -e 430842 -o analyzeFullHadronicSelection' -n 11 --name pt0470
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=1400. usePF=0" -p qcd10_pt800_pat -s 0 -e 462765 -o analyzeFullHadronicSelection' -n 15 --name pt0800
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd usePF=0" -p qcd10_pt1400_pat -s 0 -e 221277 -o analyzeFullHadronicSelection' -n 15 --name pt1400

## qcd herwig calo
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=30. usePF=0" -p qcd10_pt15_her_pat -s 0 -e 120 -o analyzeFullHadronicSelection' -n 1 --name pt0015_her
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=80. usePF=0" -p qcd10_pt30_her_pat -s 0 -e 1292 -o analyzeFullHadronicSelection' -n 1 --name pt0030_her
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=170. usePF=0" -p qcd10_pt80_her_pat -s 0 -e 25301 -o analyzeFullHadronicSelection' -n 1 --name pt0080_her
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=300. usePF=0" -p qcd10_pt170_her_pat -s 0 -e 110065 -o analyzeFullHadronicSelection' -n 2 --name pt0170_her
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=470. usePF=0" -p qcd10_pt300_her_pat -s 0 -e 151068 -o analyzeFullHadronicSelection' -n 3 --name pt0300_her
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=800. usePF=0" -p qcd10_pt470_her_pat -s 0 -e 90612 -o analyzeFullHadronicSelection' -n 3 --name pt0470_her
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd maxPtHat=1400. usePF=0" -p qcd10_pt800_her_pat -s 0 -e 58869 -o analyzeFullHadronicSelection' -n 3 --name pt0800_her
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=qcd usePF=0" -p qcd10_pt1400_her_pat -s 0 -e 27288 -o analyzeFullHadronicSelection' -n 3 --name pt1400_her

## qcd madgraph calo
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=all usePF=0" -p qcd10_pt100_mad_pat -s 0 -e 46226 -o analyzeFullHadronicSelection' -n 1 --name pt0100_mad
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=all usePF=0" -p qcd10_pt250_mad_pat -s 0 -e 380278 -o analyzeFullHadronicSelection' -n 10 --name pt0250_mad
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=all usePF=0" -p qcd10_pt500_mad_pat -s 0 -e 958891 -o analyzeFullHadronicSelection' -n 20 --name pt0500_mad
submit --cmd 'configRunner --cfg '$CMSSW_BASE'/src/TopAnalysis/Configuration/analysis/fullHadronic/cutFlow/analyzeFullHadronicSelection_cfg.py -u "eventFilter=all usePF=0" -p qcd10_pt1000_mad_pat -s 0 -e 538493 -o analyzeFullHadronicSelection' -n 15 --name pt1000_mad

