#!/bin/zsh
echo "\\\begin{table}[h]"
echo "	\\\begin{center}"
echo "		\\\caption{\\\small"
echo "		Normalised differential cross section as a function of lepton observables $ dp_T^{\\\ell}$, $\\\eta^{\\\ell}$, the transverse momentum of the lepton pair, $ p_T^{\\\ell\\\ell}$, and the invariant mass of the lepton pair $ m^{\\\ell\\\ell}$.}"
echo "		\\\label{tab:diffxseclep}"
echo "		\\\begin{tabular}{c|c||c|c|c|c}" 
echo "			\\\hline "
echo "			\\\hline            bin-center [GeV]     & bin [GeV] & $ 1/\\\sigma d\\\sigma/dp_T^{\\\ell}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "		\\\hline"
tail -n +2  combined/LeptonpTResultsLaTeX.txt
echo "			\\\hline"
echo "			\\\hline            bin-center       & bin  & $ 1/\\\sigma d\\\sigma/d\\\eta^{\\\ell}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "			\\\hline"
tail -n +2 combined/LeptonEtaResultsLaTeX.txt
echo "			\\\hline"
echo "			\\\hline            bin-center [GeV]      & bin [GeV] & $ 1/\\\sigma d\\\sigma/dp_T^{\\\ell\\\ell}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "			\\\hline "
tail -n +2 combined/LLBarpTResultsLaTeX.txt
echo "			\\\hline"
echo "			\\\hline            bin-center [GeV]      & bin [GeV] & $ 1/\\\sigma d\\\sigma/dm^{\\\ell\\\ell}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "			\\\hline"
tail -n +2 combined/LLBarMassResultsLaTeX.txt
echo "		\\\hline"
echo "  	\\\hline"
echo "		\\\end{tabular}"
echo "	\\\end{center}"
echo "\\\end{table}"

echo " "
echo "\\\begin{table}[h]"
echo "	\\\begin{center}"
echo "		\\\caption{\\\small "
echo "		Normalised differential cross section as a function of top quark observables, the transverse momentum of the top quarks, $ p_T^{t~{\\\rm or}~\\\bar{t}}$, the rapidity of the top quarks , $ y^{t~{\\\rm or}~\\\bar{t}}$, the transverse momentum of the top quark pair, $ p_T^{\\\ttbar}$ and the invariant mass of the quark pair $ m^{\\\ttbar}$.}"
echo "		\\\label{tab:diffxsectop}"
echo "		\\\begin{tabular}{c|c||c|c|c|c} "
echo "			\\\hline "
echo "			\\\hline            bin-center [GeV]      & bin [GeV] & $ 1/\\\sigma d\\\sigma/p_T^{t~{\\\rm or}~\\\bar{t}}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "		\\\hline"
tail -n +2 combined/ToppTResultsLaTeX.txt
echo "			\\\hline"
echo "			\\\hline            bin-center       & bin & $ 1/\\\sigma d\\\sigma/y^{t~{\\\rm or}~\\\bar{t}}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "			\\\hline"
tail -n +2 combined/TopRapidityResultsLaTeX.txt
echo "			\\\hline"
echo "			\\\hline            bin-center [GeV]      & bin [GeV] & $ 1/\\\sigma d\\\sigma/d p_T^{\\\ttbar}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "			\\\hline "
tail -n +2 combined/TTBarpTResultsLaTeX.txt
echo "			\\\hline" 
echo "			\\\hline            bin-center       & bin & $ 1/\\\sigma d\\\sigma/y^{\\\ttbar}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "			\\\hline"
tail -n +2 combined/TTBarRapidityResultsLaTeX.txt
echo "			\\\hline" 
echo "			\\\hline            bin-center [GeV]      & bin [GeV] & $ 1/\\\sigma d\\\sigma/dm^{\\\ttbar}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "			\\\hline"		
tail -n +2 combined/TTBarMassResultsLaTeX.txt
echo "                  \\\hline"
echo "  		\\\hline"
echo "		\\\end{tabular}"
echo "	\\\end{center}"
echo "\\\end{table}"
echo " "
echo "\\\begin{table}[h]"
echo "	\\\begin{center}"
echo "		\\\caption{\\\small"
echo "                  Normalised differential cross section as a function of b-jet observables, the transverse momentum of the b-jets, $ p_T^{b~{\\\rm or}~\\\bar{b}}$, the pseudorapidity of the b-jets, $\\\eta^{b~{\\\rm or}~\\\bar{b}}$.}"
echo "		\\\label{tab:diffxsecbjet}"
echo "		\\\begin{tabular}{c|c||c|c|c|c}"
echo "			\\\hline" 
echo "			\\\hline            bin-center [GeV]      & bin [GeV] & $ 1/\\\sigma d\\\sigma/p_T^{b~{\\\rm or}~\\\bar{b}}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "		\\\hline"
tail -n +2 combined/BJetpTResultsLaTeX.txt
echo "			\\\hline"
echo "			\\\hline            bin-center       & bin & $ 1/\\\sigma d\\\sigma/\\\eta^{b~{\\\rm or}~\\\bar{b}}$ & stat. [\\\%] & sys. [\\\%] & total [\\\%] \\\\\\"
echo "			\\\hline" 
tail -n +2 combined/BJetEtaResultsLaTeX.txt
echo "  		\\\hline"
echo "		\\\end{tabular}"
echo "	\\\end{center}"
echo "\\\end{table}"
