all:
	g++ -Wall -Wextra -O2 `root-config --cflags --libs` -lRooFit foldedLikelihoods.C -o foldedLikelihoods
	g++ -Wall -Wextra -O2 `root-config --cflags --libs`          alphaDependence.C   -o alphaDependence
