import FWCore.ParameterSet.Config as cms

filterKinFitQuality  = cms.EDFilter("KinFitQualityFilter",
    srcA             = cms.InputTag("ttFullHadEvent"),
    srcB             = cms.InputTag("selectedLayer1Jets"),
    whichFit         = cms.int32(0),
    maxChi2          = cms.double(999999.0),
    minChi2          = cms.double(0.0),
    maxProb          = cms.double(1.0),
    minProb          = cms.double(0.0),
    maxbQuarkPt      = cms.double(99999.0),
    minbQuarkPt      = cms.double(-99999.0),
    maxbQuarkEta     = cms.double(99999.0),
    minbQuarkEta     = cms.double(-99999.0),
    maxQuarkPhi      = cms.double(99999.0),
    minQuarkPhi      = cms.double(-99999.0),
    maxlightQuarkPt  = cms.double(99999.0),
    minlightQuarkPt  = cms.double(-99999.0),
    maxlightQuarkEta = cms.double(99999.0),
    minlightQuarkEta = cms.double(-99999.0),
    maxlightQuarkPhi = cms.double(99999.0),
    minlightQuarkPhi = cms.double(-99999.0),
    useEventWeight   = cms.bool(False),
    weight           = cms.InputTag("eventWeight")
)
