#!/usr/bin/perl -w

# script to run over a list of input files (use of wildcard is allowed) and
# to grep different cuts. These cuts are expected to be named AND ordered as:
#
#  1) physicsDeclared
#  2) hltLevel1GTSeed
#  3) primVtxFilter
#  4) beamScrapFilter
#  5) HBHENoiseFilter
#
#   after this general cuts two alternative filter paths are applied
#
#   a) oneHardMuon
#   b) twoGlobalMuons
#
# It sums num1 ... num7 before and after the cut was applied and puts the
# result out to screen.

# get list of input files
my @myfiles = @ARGV;

# initialize error counters
my $err1   = 0;

# initialize event counters
my $nom1   = 0;
my $nom2   = 0;
my $nom3   = 0;
my $nom4   = 0;
my $nom5   = 0;

my $denom1 = 0;
my $denom2 = 0;
my $denom3 = 0;
my $denom4 = 0;
my $denom5 = 0;

# loop over each file and accumulate the event numbers
foreach my $file (@myfiles) {

    # print current file name
    print "... processing file $file \n";

    # get the grep output from the shell

    my @primaryVertexFilter = `grep TrigReport $file | grep 'primaryVertexFilter'`;
    my @beamScrapFilter     = `grep TrigReport $file | grep 'beamScrapFilter'`;
    my @HBHENoiseFilter     = `grep TrigReport $file | grep 'HBHENoiseFilter'`;
    my @oneHardMuon         = `grep TrigReport $file | grep 'oneHardMuon'`;
    my @twoGlobalMuons      = `grep TrigReport $file | grep 'twoGlobalMuons'`;    
    
    # check the pattern and extract the numbers, if succesful
    # accumulate else voice error message ; first occurrence
    # semi leptonic second dileptonic preselection

    my $failed = 0;
    
    if($primaryVertexFilter[0] =~ /TrigReport\s+\d\s+\d\s+(\d+)\s+(\d+).*/) {
      $nom1   = $nom1   + $2;
      $denom1 = $denom1 + $1;
    } else {
      $failed = 1;
      print ">> ERROR: didn't find primaryVertexFilter from $file <<\n";
      print $primaryVertexFilter[0]
    };      
      
    if($beamScrapFilter[0] =~ /TrigReport\s+\d\s+\d\s+(\d+)\s+(\d+).*/) {
      $nom2   = $nom2   + $2;
      $denom2 = $denom2 + $1;
    } else {
      $failed = 1;
      print ">> ERROR: didn't find beamScrapFilter from $file <<\n";
      print $beamScrapFilter[0]
    }; 
    
    if($HBHENoiseFilter[0] =~ /TrigReport\s+\d\s+\d\s+(\d+)\s+(\d+).*/) {
      $nom3   = $nom3   + $2;
      $denom3 = $denom3 + $1;
    } else {
      $failed = 1;
      print ">> ERROR: didn't find HBHENoiseFilter from $file <<\n";
      print $HBHENoiseFilter[0]
    }; 
            
    if($oneHardMuon[0] =~ /TrigReport\s+\d\s+\d\s+(\d+)\s+(\d+).*/) {
      $nom4   = $nom4   + $2;
      $denom4 = $denom4 + $1;
    } else {
      $failed = 1;
      print ">> ERROR: didn't find oneHardMuon from $file <<\n";
      print $oneHardMuon[0]
    };   
    
    if($twoGlobalMuons[0] =~ /TrigReport\s+\d\s+\d\s+(\d+)\s+(\d+).*/) {
      $nom5  = $nom5   + $2;
      $denom5 = $denom5 + $1;
    } else {
      $failed = 1;
      print ">> ERROR: didn't find twoGlobalMuons from $file <<\n";
      print $twoGlobalMuons[0]
    };             
    
    if($failed == 1){ $err1 = $err1 + 1 }
  }; # end loop over files

# output record
print "\n";
print "----------------------------------------------";
print "\n  Accumulated errors    :\n";
print "----------------------------------------------";
print "\n";
print "  N/A record: \t $err1 \n";
print "----------------------------------------------";
print "\n  Accumulated statistics:\n";
print "----------------------------------------------";
print "\n                 \t before: \t\t after: \n";
print "    primVtxFilter: \t $denom1 \t\t $nom1 \n";
print "  beamScrapFilter: \t $denom2 \t\t $nom2 \n";
print "  HBHENoiseFilter: \t $denom3 \t\t $nom3 \n\n";
print "      oneHardMuon: \t $denom4 \t\t $nom4 \n";
print "   twoGlobalMuons: \t $denom5 \t\t $nom5 \n";
print "----------------------------------------------\n";

exit;
