#!/bin/zsh

echo modified files in current CVS tree
cvs status 2>&1 | awk '{
  if ($1 == "?") if ($2 ~ /__init__.py/){} else print "\033[34mnew:\033[m "$2
  else if ($3=="Examining") {currentDir=$4}
  else if ($1=="File:" && $4!="Up-to-date") {
     if ($4=="Needs") {
        if ($5=="Patch") status="\033[32moutdated:\033[m";
        if ($5=="Merge") status="\033[41mmerge needed:\033[m";
     }
     else if ($4=="Locally") {
        if ($5=="Modified") status="\033[31mmodified:\033[m";
        if ($5=="Added") status="\033[31mneeds commit\033[m \033[34m(new)\033[m:";
     }
     else if ($4=="Entry" && $5=="Invalid") {
        status="\033[32mremoved upstream:\033[m";
     }
     else if ($6=="Needs" && $7=="Checkout") {
        status="\033[31mlocally lost:\033[m";
        $2=$4;
     }
     else if ( $6=="Locally" && $7=="Removed" ) {
        status="\033[31mneeds commit\033[m \033[41m(removed)\033[m:";
        $2=$4;
     }
     else if ( $4=="File" && $5=="had" && $6=="conflicts" && $7=="on" && $8=="merge") {
        status="\033[41mhad merge conflict:\033[m";
     }
     else status="unsupported status:";

     print status" "currentDir"/"$2
  }
}'

