#! /usr/bin/env python

# based on script by Salvatore Rappoccio
# sums summary tables of splitted jobs
# run eg with 
# ' triggerReport crab_0_xxxxxx_yyyyyy/res/CMSSW_*.stdout
 
import re
import sys
import os.path

p = re.compile(r'\W+')


# modules in TrigReport summary tables
tokens = ['analyzePrimaryVertex',
	  'filterTrigger',
	  'tightMuons',
	  'oneTightMuonSelection',
          'trackerMuons',
	  'oneTrackerMuonSelection',
	  'globalMuons',
	  'oneGlobalMuonSelection',
	  'hardMuons',
	  'oneHardMuonSelection',
	  'goodTrackMuons',
	  'oneGoodTrackMuonSelection',
	  'muHitMuons',
	  'oneMuHitMuonSelection',
	  'goodD0Muons',
	  'oneGoodD0MuonSelection',
	  'goodMuons',
	  'oneGoodMuonSelection',
	  'cleanPatMuons',
	  'cleanPatElectrons',
	  'cleanPatPhotons',
	  'cleanPatTaus',
	  'cleanPatJets',
	  'cleanPatCandidateSummary',
	  'tightJets',
	  'goodJets',
	  'hardJets',
	  'analyzeGoodMuonsStep1',
	  'analyzeHardJetsStep1',
	  'analyzeMETStep1',
	  'twoTightMuonSelection',
	  'twoTrackerMuonSelection',
	  'twoGlobalMuonSelection',
	  'twoHardMuonSelection',
	  'twoGoodTrackMuonSelection',
	  'twoMuHitMuonSelection',
	  'twoGoodD0MuonSelection',
	  'twoGoodMuonSelection',
	  'analyzeGoodMuonsStep2',
	  'analyzeGoodMuonPairStep2',
	  'analyzeHardJetsStep2',
	  'analyzeMETStep2',
	  'isolatedMuons',
	  'twoIsolatedMuonSelection',
	  'analyzeIsolatedMuonsStep3',
	  'analyzeIsolatedMuonPairStep3',
	  'analyzeHardJetsStep3',
	  'analyzeMETStep3',
	  'oneTightJetSelection',
	  'oneGoodJetSelection',
	  'oneHardJetSelection',
	  'analyzeIsolatedMuonsStep4',
	  'analyzeIsolatedMuonPairStep4',
	  'analyzeHardJetsStep4',
	  'analyzeMETStep4',
	  'filterDiMuonMassQCDveto',
	  'analyzeIsolatedMuonsStep5',
	  'analyzeHardJetsStep5',
	  'analyzeMETStep5',
	  'filterDiMuonMassZveto',
	  'analyzeIsolatedMuonsStep6',
	  'analyzeHardJetsStep6',
	  'analyzeMETStep6',
	  'highMETs',
	  'metSelection',
	  'analyzeIsolatedMuonsStep7',
	  'analyzeHardJetsStep7',
	  'twoTightJetSelection',
	  'twoGoodJetSelection',
	  'twoHardJetSelection',
	  'kinSolutionTtFullLepEventHypothesis',
	  'ttFullLepHypKinSolution',
	  'ttFullLepEvent',
	  'filterHypoValidity',
	  'analyzeKinSolution1'
	 ]

print 'TrigReport ---------- Modules in Path: p ------------'
print 'TrigReport  Trig Bit#    Visited     Passed     Failed      Error Name'

for s in tokens:
#    print 'Looking at string ' + s

    nvisit = 0
    npass = 0
    nfail = 0
    nerror = 0
    for i in range(1,len(sys.argv) ) :
#        print 'Opening file ' + sys.argv[i]
        infile = open(sys.argv[i], 'r')
    
        for line in infile :
            if ( line.find(s) >= 0 ) :
#                print 'found! line = ',line
#                print p.split(line)
                nvisit += int(p.split(line)[3])
                npass  += int(p.split(line)[4])
                nfail  += int(p.split(line)[5])
                nerror += int(p.split(line)[6])
                break
        infile.close()
    print 'TrigReport     1    0  %9d' % nvisit,'%10d' % npass,'%10d' % nfail, '%10d' % nerror, s
