#include <utility>
#include <algorithm>
#include "TopAnalysis/TopAnalyzer/plugins/GenLevelBJetAnalyzer.h"

//
// constructors and destructor
//
/**
* @brief constructor initialising producer products and config parameters
*
* Output generated by this producer:
* <TABLE>
* <TR><TH> name                </TH><TH> type                           </TH><TH> description </TH> </TR>
* <TR><TD> BHadJetIndex        </TD><TD> std::vector<int>               </TD><TD> position of the jet identified as b-hadron jet in the input GenJetCollection </TD></TR>
* <TR><TD> BHadrons            </TD><TD> std::vector<reco::GenParticle> </TD><TD> vector of the identified b-hadrons (definition of b-hadron and anti-b-hadron below) </TD></TR>
* <TR><TD> BHadronFromTopB     </TD><TD> std::vector<bool>              </TD><TD> true if the corresponding b-hadron originates from the ttGenEvent b-quark </TD></TR>
* <TR><TD> BHadronVsJet        </TD><TD> std::vector<int>               </TD><TD> matrix of which b-hadron appears in which GenJet, access by [iJet * BHadrons.size() + iBhadron] </TD></TR>
*
* <TR><TD> AntiBHadJetIndex    </TD><TD> std::vector<int>               </TD><TD> position of the jet identified as anti-b-hadron jet in the input GenJetCollection </TD></TR>
* <TR><TD> AntiBHadrons        </TD><TD> std::vector<reco::GenParticle> </TD><TD> vector of the identified anti-b-hadrons (definition of b-hadron and anti-b-hadron below) </TD></TR>
* <TR><TD> AntiBHadronFromTopB </TD><TD> std::vector<bool>              </TD><TD> true if the corresponding anti-b-hadron originates from the ttGenEvent anti-b-quark </TD></TR>
* <TR><TD> AntiBHadronVsJet    </TD><TD> std::vector<int>               </TD><TD> matrix of which anti-b-hadron appears in which GenJet, access by [iJet * AntiBHadrons.size() + iBhadron] </TD></TR>
*
* </TABLE>
*
* @warning Definition of b-hadron and anti-b-hadron: The term b-hadron and anti-b-hadron is in reference to the quark content and <b>not</b> to distinguish particles from anti-particles.
* Here a b-hadron contains a b-quark and an anti-b-hadron contains an anti-b-quark.
* For mesons this means an inversion with respect to the PDG definition, as mesons actually contain anti-b-quarks and anti-mesons contain b-quarks.
*
*/
GenLevelBJetAnalyzer::GenLevelBJetAnalyzer ( const edm::ParameterSet& cfg )
{

    ttGenEvent_        = cfg.getParameter<edm::InputTag> ( "ttGenEvent" );
    genJets_           = cfg.getParameter<edm::InputTag> ( "genJets" );
    deltaR_            = cfg.getParameter<double> ( "deltaR" );
    flavour_           = cfg.getParameter<int> ( "flavour" );
    noBBbarResonances_ = cfg.getParameter<bool> ( "noBBbarResonances" );
    requireTopBquark_  = cfg.getParameter<bool> ( "requireTopBquark" );
    resolveName_       = cfg.getParameter<bool> ( "resolveParticleName" );
    doImprovedHadronMatching_ = cfg.getParameter<bool> ( "doImprovedHadronMatching" );
    doValidationPlotsForImprovedHadronMatching_ = cfg.getParameter<bool> ( "doValidationPlotsForImprovedHadronMatching" );

    if ( !doImprovedHadronMatching_ ) {
        doValidationPlotsForImprovedHadronMatching_=false;
    }
    toPlot = doValidationPlotsForImprovedHadronMatching_;


    flavour_ = abs ( flavour_ ); // Make flavour independent of sign given in configuration
    if ( flavour_==5 ) {
        flavourStr_="B";
    } else if ( flavour_==4 ) {
        flavourStr_="C";
    } else {
        edm::LogError ( "GenLevelBJetAnalyzer" ) << "Flavour option must be 4 (c-jet) or 5 (b-jet), but is: " << flavour_ << ". Correct this!";
    }


    if ( !doImprovedHadronMatching_ ) {
        return;
    }


    if ( !doValidationPlotsForImprovedHadronMatching_ ) {
        return;
    }

// Initializing ROOT file for storing histograms
    edm::Service<TFileService> fs;
    if( !fs ) throw edm::Exception( edm::errors::Configuration, "TFile Service is not registered in cfg file" );

    h_nHad = fs->make<TH1I> ( "nHad", "Nr. of hadrons;N", 10, 0, 10 );
    h_hadJetIndex = fs->make<TH1I> ( "hadJetIndex", "Index of hadron jet;index;hadrons", 102, -2, 100 );
    h_jetdPt = fs->make<TH1D> ( "jetdPt", "#DeltaPt(Clust/dR);#DeltaPt(Clust/dR)", 50, 0, 3 );
    h_jetDeltaPt = fs->make<TH1D> ( "jetDeltaPt", "#DeltaPt(Clust-dR);#DeltaPt [GeV]", 50, -100, 100 );

    h2_QQMothSamePdg = fs->make<TH2D> ( "QQMothSamePdg", "PdgId of quark and mother quark with same abs(pdgId);Daughter PdgId;Mother PdgId", 14, -7, 7,14,-7,7 );
    h_QQMothEFrac = fs->make<TH1D> ( "QQMothEFrac", "E fraction of daughter;#frac{E}{E^{mother}}", 50, 0., 10.0 );
    h_QHQPtFrac = fs->make<TH1D> ( "QHQPtFrac", "Pt fraction of highest Pt daughter;#frac{Pt^{highest}-Pt}{Pt^{highest}}", 50, 0., 1.01 );
    h_QQMothdR = fs->make<TH1D> ( "QQMothdR", "dR between mother and same pdgId daughters;dR", 100, 0.0, 5.0 );
    h_QQMothdR_min = fs->make<TH1D> ( "QQMothdR_min", "Min. dR between mother and same pdgId daughters;dR", 100, 0.0, 5.0 );
    h_QHQdR = fs->make<TH1D> ( "QHQdR", "dR between mother and highest Pt daughter;dR", 100, 0.0, 5.0 );

    h_QQMothEFrac_ambig = fs->make<TH1D> ( "QQMothEFrac_ambig", "E fraction of daughter;#frac{E}{E^{mother}}", 50, 0., 10.0 );
    h_QHQPtFrac_ambig = fs->make<TH1D> ( "QHQPtFrac_ambig", "Pt fraction of highest Pt daughter;#frac{Pt^{highest}-Pt}{Pt^{highest}}", 50, 0., 1.01 );
    h_QQMothdR_ambig = fs->make<TH1D> ( "QQMothdR_ambig", "dR between mother and same pdgId daughters;dR", 100, 0.0, 5.0 );
    h_QQMothdR_min_ambig = fs->make<TH1D> ( "QQMothdR_min_ambig", "Min. dR between mother and same pdgId daughters;dR", 100, 0.0, 5.0 );
    h_QHQdR_ambig = fs->make<TH1D> ( "QHQdR_ambig", "dR between mother and highest Pt daughter;dR", 100, 0.0, 5.0 );

    h_jetHad_dR = fs->make<TH1D> ( "jetHad_dR", "dR between hadron and jet matched by jet clustering algo;dR_{hadron}^{jet}", 50, 0, 4 );
    h_jetHadOld_dR = fs->make<TH1D> ( "jetHadOld_dR", "dR between hadron and jet matched by decay products;dR_{hadron}^{jet}", 50, 0, 4 );
    h_jetHadOldNoMatch_dR = fs->make<TH1D> ( "jetHadOldNoMatch_dR", "dR between hadron and jet matched by decay products;dR_{hadron}^{jet}", 50, 0, 4 );
    h_jetHad_dR_noFlav = fs->make<TH1D> ( "jetHad_dR_noFlav", "dR between hadron and jet matched by jet clustering algo;dR_{hadron}^{jet}", 50, 0, 4 );
    h_jetHadOldNoMatch_dR_noFlav = fs->make<TH1D> ( "jetHadOldNoMatch_dR_noFlav", "dR between hadron and jet matched by decay products;dR_{hadron}^{jet}", 50, 0, 4 );

    h_hadJet_dRmin = fs->make<TH1D> ( "hadJet_dRmin", "Min dR between hadron and any jet;dR_{hadron}^{jet}", 50, 0, 4 );

    h_nFirstQ = fs->make<TH1I> ( "nFirstQ", "Number of the 1-st quarks;N", 10, 0, 10 );
    h_firstQstatus = fs->make<TH1I> ( "firstQstatus", "Status of the 1-st quark;status", 5, 0, 5 );
    h_firstQPdg = fs->make<TH1I> ( "firstQPdg", "PdgId of the 1-st quark;PdgId", 60, -30, 30 );
    h2_firstQFlav_HadFlav = fs->make<TH2D> ( "firstQFlav_HadFlav", "Charge of the 1-st quark and hadron;Hadron charge;Quark charge", 5, -2, 3, 5,-2,3 );
    h2_firstQFlav_QMotherFlav = fs->make<TH2D> ( "firstQMotherFlav_QMotherFlav", "Charge of the 1-st quark and its mother;Quark charge;Quark's mother charge", 5, -2, 3, 5, -2, 3 );
    h_nLastQ = fs->make<TH1I> ( "nLastQ", "Number of the last quarks;N", 10, 0, 10 );
    h_lastQstatus = fs->make<TH1I> ( "lastQstatus", "Status of the last quark;status", 5, 0, 5 );
    h_lastQPdg = fs->make<TH1I> ( "lastQPdg", "PdgId of the last quark;PdgId", 60, -30, 30 );
    h2_lastQFlav_HadFlav = fs->make<TH2D> ( "lastQFlav_HadFlav", "Charge of the last quark and hadron;Hadron charge;Quark charge", 5, -2, 2,5,-2,2 );
    h2_lastQFlav_QMotherFlav = fs->make<TH2D> ( "lastQFlav_QMotherFlav", "Charge of the last quark and its mother;Quark charge;Quark's mother charge", 5, -2, 3,5,-2,3 );
    h2_lastQPdg_QMotherPdg = fs->make<TH2D> ( "lastQPdg_QMotherPdg", "PdgId of the last quark and its mother;Quark pdgId;Quark's mother pdgId", 13, -6, 7,35,-8,27 );
    h_lastQ_lastQ_dRmin = fs->make<TH1D> ( "lastQ_lastQ_dRmin", "dR_{min} between hadron and closest last quark;dR_{hadron}^{Quark}", 50, 0, 4 );

    h_nHadTop = fs->make<TH1I> ( "nHadTop", "Nr. of hadrons from Top;N", 10, 0, 10 );
    h_nHadHiggs = fs->make<TH1I> ( "nHadHiggs", "Nr. of hadrons from Higgs;N", 10, 0, 10 );
    h_nHadGluon = fs->make<TH1I> ( "nHadGluon", "Nr. of hadrons from Gluon;N", 10, 0, 10 );
    h_nHadZ = fs->make<TH1I> ( "nHadZ", "Nr. of hadrons from Z;N", 10, 0, 10 );
    h_nHadNo = fs->make<TH1I> ( "nHadNo", "Nr. of hadrons without flavour;N", 10, 0, 10 );

    h_nHadInJet = fs->make<TH1I> ( "nHadInJet", "N hadrons associated to a jet;N hadrons;Jets", 10, 0, 10 );
    h_hadFlavour = fs->make<TH1I> ( "hadFlavour", "Flavour of the hadron origin;Flavour;Hadron", 60, -30, 30 );
}

GenLevelBJetAnalyzer::~GenLevelBJetAnalyzer()
{
}


// ------------ method fills 'descriptions' with the allowed parameters for the module  ------------
/**
* @brief description of the run-time parameters
*
* <TABLE>
* <TR><TH> name                </TH><TH> description </TH> </TR>
* <TR><TD> ttGenEvent          </TD><TD> input collection of TtGenEvent, used to identify the b-quark from top </TD></TR>
* <TR><TD> genJets             </TD><TD> input GenJet collection </TD></TR>
* <TR><TD> deltaR              </TD><TD> maximum angle between hadron and GenJet </TD></TR>
* <TR><TD> noBBbarResonances   </TD><TD> exclude resonances to be identified as hadrons </TD></TR>
* <TR><TD> requireTopBquark    </TD><TD> only accept hadrons coming from the top-quark </TD></TR>
* <TR><TD> resolveParticleName </TD><TD> print particle name during warning and debug output instead of PDG ID </TD></TR>
* <TR><TD> flavour		</TD><TD> flavour of weakly decaying hadron that the jets should be matched to (5-b, 4-c) </TD></TR>
* </TABLE>
*
*/
// void GenLevelBJetAnalyzer::fillDescriptions ( edm::ConfigurationDescriptions& descriptions )
// {
// 
//     edm::ParameterSetDescription desc;
//     desc.add<edm::InputTag> ( "ttGenEvent",edm::InputTag ( "genEvt" ) )->setComment ( "Input collection of TtGenEvent, used to identify the quark from top" );
//     desc.add<edm::InputTag> ( "genJets",edm::InputTag ( "ak5GenJets","","HLT" ) )->setComment ( "Input GenJet collection" );
//     desc.add<double> ( "deltaR",.5 )->setComment ( "Maximum angle between hadron and GenJet" );
//     desc.add<bool> ( "noBBbarResonances",true )->setComment ( "Exclude resonances to be identified as hadrons" );
//     desc.add<bool> ( "requireTopBquark",false )->setComment ( "Only accept hadrons coming from the top-quark" );
//     desc.add<bool> ( "resolveParticleName",false )->setComment ( "Print particle name during warning and debug output instead of PDG ID" );
//     desc.add<int> ( "flavour",5 )->setComment ( "Flavour of weakly decaying hadron that should be added to the jet for futher tagging. (4-c, 5-b)" );
//     desc.add<bool> ( "doImprovedHadronMatching",false )->setComment ( "Whether to store improved information about bHadron-bQuark-Jet matching." );
//     desc.add<bool> ( "doValidationPlotsForImprovedHadronMatching",false )->setComment ( "Whether to store validation plots for improved matching." );
//     descriptions.add ( "analyzeGenLevelBJet",desc );
// }



//
// member functions
//

// ------------ method called to produce the data  ------------
void GenLevelBJetAnalyzer::analyze ( const edm::Event& evt, const edm::EventSetup& setup )
{

    setup.getData ( pdt_ );

    using namespace edm;

    // printf("Run: %d\tLumi: %d\tEvent: %d\n",(int)evt.eventAuxiliary().run(), (int)evt.eventAuxiliary().luminosityBlock(), (int)evt.eventAuxiliary().event());

    std::auto_ptr<std::vector<int> > bIdx ( new std::vector<int> );
    std::auto_ptr<std::vector<int> > anti_bIdx ( new std::vector<int> );
    std::auto_ptr<std::vector<int> > bHadronVsJet ( new std::vector<int> );
    std::auto_ptr<std::vector<int> > anti_bHadronVsJet ( new std::vector<int> );
    std::auto_ptr<std::vector<reco::GenParticle> > bHadrons ( new std::vector<reco::GenParticle> );
    std::auto_ptr<std::vector<reco::GenParticle> > anti_bHadrons ( new std::vector<reco::GenParticle> );
    std::auto_ptr<std::vector<bool> > bHadronFromTopBqark ( new std::vector<bool> );
    std::auto_ptr<std::vector<bool> > anti_bHadronFromTopBqark ( new std::vector<bool> );

    edm::Handle<TtGenEvent> genEvt;
    evt.getByLabel ( ttGenEvent_, genEvt );

    edm::Handle<reco::GenJetCollection> genJets;
    evt.getByLabel ( genJets_, genJets );

    LogDebug ( "bJet" ) << "searching for b-jets in " << genJets_;
    *bIdx = getGenJetWith ( genEvt->b(), *genJets, *bHadrons, *bHadronFromTopBqark, *bHadronVsJet );
    LogDebug ( "bJet" ) << "searching for anti-b-jets in " << genJets_;
    *anti_bIdx = getGenJetWith ( genEvt->bBar(), *genJets, *anti_bHadrons, *anti_bHadronFromTopBqark, *anti_bHadronVsJet );

    if ( !doImprovedHadronMatching_ ) {
        return;
    }

// Additional information -------------------------->>>>>>>>>>>

// Hadron matching variables
    std::auto_ptr<std::vector<reco::GenParticle> > hadMothers ( new std::vector<reco::GenParticle> );
    std::auto_ptr<std::vector<std::vector<int> > > hadMothersIndices ( new std::vector<std::vector<int> > );
    std::auto_ptr<std::vector<int> > hadIndex ( new std::vector<int> );
    std::auto_ptr<std::vector<int> > hadFlavour ( new std::vector<int> );
    std::auto_ptr<std::vector<int> > hadJetIndex ( new std::vector<int> );

    LogDebug ( flavourStr_+"Jet (new)" ) << "searching for "<< flavourStr_ <<"-jets in " << genJets_;
    *hadJetIndex = findHadronJets ( *genJets, *hadIndex, *hadMothers, *hadMothersIndices, *hadFlavour );

}

// ------------ method called once each job just before starting event loop  ------------
void GenLevelBJetAnalyzer::beginJob()
{
}

// ------------ method called once each job just after ending the event loop  ------------
void GenLevelBJetAnalyzer::endJob()
{
}

// ------------ method called when starting to processes a run  ------------
void GenLevelBJetAnalyzer::beginRun ( edm::Run&, edm::EventSetup const& )
{
}

// ------------ method called when ending the processing of a run  ------------
void
GenLevelBJetAnalyzer::endRun ( edm::Run&, edm::EventSetup const& )
{
}

// ------------ method called when starting to processes a luminosity block  ------------
void GenLevelBJetAnalyzer::beginLuminosityBlock ( edm::LuminosityBlock&, edm::EventSetup const& )
{
}

// ------------ method called when ending the processing of a luminosity block  ------------
void GenLevelBJetAnalyzer::endLuminosityBlock ( edm::LuminosityBlock&, edm::EventSetup const& )
{
}

// ------------ helper functions -------------

/**
* @brief identify the jets that contain b-hadrons
*
* All jets originating from a b-hadron with the right b content (b or anti-b) are identified in the GenJetCollection.
* This is done by searching through the generator particle decay tree starting from the constituents of the generator jets.
* The b-hadron which is lowest in the decay-chain (just before the weak decay of the b) is considered the b-hadron of this jet.
* Only jets within the given @f$\delta_{r}@f$ to the b-hadron are accepted.
* In case more than one jet originates from the same b-hadron, the jet which is nearer in @f$\delta_{r}@f$ is chosen.
*
* b-bbar resonances can either be considered b-hadrons or not depending on the configuration.
*
* The b-hadrons can be required to originate from the given b-quark depending on the configuration.
*
* To allow performance studies following informations are tracked and returned:
* \arg the GenParticles identified as b-hadrons
* \arg if the b-hadron originates from the top-b-quark
* \arg a matrix showing which jets contain particles from which b-hadron
*
* @param[in] bQuark used to set the charge of the b-Hadrons
* @param[in] genJets the GenJetCollection to be searched
* @param[out] bHadronObjects list of identified b-hadrons
* @param[out] isFromBquark tells which bHadrons originate from the given b-quark
* @param[out] bHadronsInJet relation between b-hadron and genJets. 0 => no daughters of bHadron in this jet, 1 => daughters of this bHadron in this jet. Access (iJet,iBhadron) -> [iJet * bHadronObject.size() + iBhadron]
* @returns a list with the indicies of the GenJets that fulfill the requirements
*/
std::vector<int> GenLevelBJetAnalyzer::getGenJetWith ( const reco::Candidate* bQuark, const reco::GenJetCollection& genJets, std::vector<reco::GenParticle> &bHadronObjects, std::vector<bool> &isFromBquark, std::vector<int> &bHadronsInJet )
{

    std::vector<int> result;
    if ( ! bQuark ) {
        return result;    //no b-quark given, so so b-jets
    }

    std::vector<const reco::GenJet*> bQuarkCandidates;
    std::vector<const reco::GenJet*> bHadronCandidates;
    std::vector<size_t> bQuarkCandidateIndex;
    std::vector<size_t> bHadronCandidateIndex;
    std::vector<unsigned int> nBquarkParticles;
    std::vector<unsigned int> nBhadronParticles;
    std::vector<const reco::Candidate*> motherBhadron;

    typedef std::map<double, const reco::Candidate*> bHadronMap_t;
    bHadronMap_t bHadronList;
    typedef std::map<double, bool> bHadronFlagMap_t;
    bHadronFlagMap_t bHadronFlags;
    typedef std::map<double, std::vector<size_t> > jetCandidatesVsBhadron_t;
    jetCandidatesVsBhadron_t jetCandidatesVsBhadron;

    for ( size_t iJet = 0; iJet < genJets.size(); ++iJet ) {
        const reco::GenJet* thisJet = & ( genJets[iJet] );
        std::vector<const reco::GenParticle*> particles = thisJet->getGenConstituents();


        LogTrace ( "Jets" ) << printJetInfo ( iJet, thisJet );

        bool isBquarkCandidate = false;
        bool isBhadronCandidate = false;
        unsigned int nBquarkDaughters = 0;
        unsigned int nBhadronDaughters = 0;
        bHadronMap_t bHadrons;

        for ( unsigned int iParticle = 0; iParticle < particles.size(); ++iParticle ) {
            const reco::GenParticle* thisParticle = particles[iParticle];
            const reco::Candidate* bHadron = 0;
            std::vector<const reco::Candidate*> particleChain;
            checkForLoop ( particleChain,thisParticle );
            if ( searchInMothers ( bQuark, thisParticle, particleChain, &bHadron ) ) {
                isBquarkCandidate = true;
                ++nBquarkDaughters;
                if ( bHadron ) {
                    bHadronFlags[bHadron->p()] = true;
                }
            }
            if ( bHadron ) {
                isBhadronCandidate = true;
                ++nBhadronDaughters;
                bHadrons[bHadron->p()] = bHadron;
                bHadronList[bHadron->p()] = bHadron;
            }
        }
        if ( isBquarkCandidate ) {
            bQuarkCandidates.push_back ( thisJet );
            bQuarkCandidateIndex.push_back ( iJet );
            nBquarkParticles.push_back ( nBquarkDaughters );
        }
        if ( isBhadronCandidate && ( isBquarkCandidate || !requireTopBquark_ ) ) {
            bHadronCandidates.push_back ( thisJet );
            bHadronCandidateIndex.push_back ( iJet );
            nBhadronParticles.push_back ( nBhadronDaughters );
            motherBhadron.push_back ( bHadrons.begin()->second );
            for ( bHadronMap_t::iterator it = bHadrons.begin(); it != bHadrons.end(); ++it ) {
                if ( it->second->pt() > motherBhadron.back()->pt() ) {
                    motherBhadron.back() = it->second;    // this is only for debug output and not the real decision
                }
                jetCandidatesVsBhadron[it->first].push_back ( iJet );
            }
        }
    }

// debug output no functionality
#ifdef EDM_ML_DEBUG
    LogTrace ( "bQuark" )  << "found " << bQuarkCandidates.size() << " jets with b-quark particles" << std::endl;
    LogTrace ( "bHadron" ) << "found " << bHadronCandidates.size() << " jets with b-hadron particles" << std::endl
                           << "found " << bHadronList.size() << " different b-Hadrons" << std::endl;

    for ( unsigned int i = 0; i < bQuarkCandidates.size(); ++i ) {
        const reco::GenJet *jet = bQuarkCandidates.at ( i );
        size_t index = bQuarkCandidateIndex.at ( i );
        LogTrace ( "bQuark" ) << "GenJet " << index << " has " << nBquarkParticles.at ( i ) << "/" << jet->getGenConstituents().size() << " b-quark daughters" << std::endl
                              << "GenJet " << index << " " << jet->p4() << " p: " << jet->p() << " p_T: " << jet->pt() << std::endl
                              << "GenJet " << index << " eta: " << jet->eta() << " phi: " << jet->phi() << std::endl;
    }


    for ( unsigned int i = 0; i < bHadronCandidates.size(); ++i ) {
        const reco::GenJet *jet = bHadronCandidates.at ( i );
        size_t index = bHadronCandidateIndex.at ( i );
        const reco::Candidate *bMother = motherBhadron.at ( i );
        LogTrace ( "bHadron" ) << "GenJet " << index << " has " << nBhadronParticles.at ( i ) << "/" << jet->getGenConstituents().size() << " b-hadron daughters" << std::endl
                               << "GenJet " << index << " " << jet->p4() << " p: " << jet->p() << " p_T: " << jet->pt() << std::endl
                               << "GenJet " << index << " eta: " << jet->eta() << " phi: " << jet->phi() << std::endl
                               << "GenJet " << index << " mother b-hadron: " << getParticleName ( bMother->pdgId() ) <<  std::endl
                               << "GenJet " << index << " mother b-hadron: " << bMother->p4() << " p: " << bMother->p() << " p_T: " << bMother->pt() << std::endl
                               << "GenJet " << index << " mother b-hadron: eta: " << bMother->eta() << " phi: " << bMother->phi() << std::endl;
    }
#endif // EDM_ML_DEBUG -- debug output


    bHadronObjects.clear();
    isFromBquark.clear();
    bHadronsInJet.clear();

    unsigned int nJets = genJets.size();
    unsigned int nBhadrons = bHadronList.size();

    bHadronsInJet.resize ( nJets*nBhadrons,0 );

    for ( jetCandidatesVsBhadron_t::iterator it = jetCandidatesVsBhadron.begin(); it != jetCandidatesVsBhadron.end(); ++it ) {

        const reco::Candidate *bHadron = bHadronList[it->first];
        std::vector<size_t> candidateIdx = it->second;
        LogTrace ( "bHadron" ) << "analysing jets for " << getParticleName ( bHadron->pdgId() ) << std::endl;
        LogTrace ( "bHadron" ) << "   " << candidateIdx.size() <<  " candidate jets: ";

        unsigned int bHadronIndex = bHadronObjects.size();
        bHadronObjects.push_back ( * ( dynamic_cast<const reco::GenParticle*> ( bHadron ) ) );
        isFromBquark.push_back ( bHadronFlags[it->first] );

        std::vector<const reco::GenJet*> jetCandidates;
        for ( unsigned int idx = 0; idx < candidateIdx.size(); ++idx ) {
            LogTrace ( "bHadron" ) << "     " << candidateIdx[idx] << std::endl;
            jetCandidates.push_back ( & ( genJets[candidateIdx[idx]] ) );
            bHadronsInJet.at ( candidateIdx[idx]*nBhadrons + bHadronIndex ) = 1;
        }

        int bestJet = getGenJetNear ( bHadron, jetCandidates );
        if ( bestJet >= 0 ) {
            result.push_back ( candidateIdx.at ( bestJet ) );
            LogTrace ( "bHadron" ) << "    best matching jet: " << candidateIdx.at ( bestJet ) << std::endl;
        } else {
            LogTrace ( "bHadron" ) << "    no matching jet in cone of " << deltaR_ << std::endl;
        }
    }

    std::sort ( result.begin(),result.end() );

    return result;
}

/**
* @brief do a recursive search for the mother particles until the b-quark is found or the absolute mother is found
*
* the treatment of b-bar resonances depends on the global parameter noBBbarResonances_
*
* @param[in] bQuark ancestor b-quark for the current search
* @param[in] thisParticle current particle to be analysed
* @param[in] particleChain current version of the search path
* @param[out] bHadron the oldest b-hadron found in the search
*
* @returns if the b-quark was found or not
*/
bool GenLevelBJetAnalyzer::searchInMothers ( const reco::Candidate* bQuark, const reco::Candidate* thisParticle, std::vector<const reco::Candidate*> particleChain, pCRC *bHadron )
{

    if ( *bHadron == 0 // find only the first b-hadron on the way (the one that decays weekly)
            && ( thisParticle->pdgId() / 1000  == bQuark->pdgId()  // b-baryions
                 || ( thisParticle->pdgId() / 100 % 10 == -bQuark->pdgId() // b-mesons
                      && ! ( noBBbarResonances_ && thisParticle->pdgId() / 10 % 100 == 55 ) // but not a b-bbar resonance
                    ) )
       ) {
        *bHadron = thisParticle;
    }

    for ( size_t iMother = 0; iMother < thisParticle->numberOfMothers(); ++iMother ) {
        const reco::Candidate* mother = thisParticle->mother ( iMother );
        if ( checkForLoop ( particleChain, mother ) ) {
            edm::LogWarning ( "decayChain" ) << "Identified a loop in the current decay chain."
                                             << " Paricle " << mother
                                             << " PDG: " << mother->pdgId()
//       << " " << mother->p4()
                                             << " pt: " << mother->pt() << ", eta: " << mother->eta()
                                             << " is already in the chain."
                                             << " Will stop this branch here. B-hadron identification might be incomplete."
                                             << " " << printParticleChain ( particleChain,*bHadron );
            return false;
        }
        if ( bQuark->p4() == mother->p4() && bQuark->pdgId() == mother->pdgId() && bQuark->status() == mother->status() ) {
            LogTrace ( "decayChain" ) << printParticleChain ( particleChain,*bHadron );
            return true;
        } else if ( searchInMothers ( bQuark, mother, particleChain, bHadron ) ) {
            return true;
        }
    }

    return false;
}

/**
* @brief identify the jets that contain b-hadrons
*
* All jets originating from a b-hadron with the right b (c) content (b or anti-b) are identified in the GenJetCollection.
* The b (c) jet is identified by searching for a hadron of corresponding flavour in the jet. Hadron are put in jets
* by "TopAnalysis.TopUtils.GenJetParticles" plugin.
* For each hadron all mothers from all levels and chains are analyzed to find the quark or gluon from which the hadron has originated.
* This is done by searching through the generator particle decay tree starting from the hadron, performing checks for flavour and kinematic consistency.
* The hadrons that are not last in the decay chain (don't decay weakly) are skipped.
*
* b-bbar (c-cbar) resonances can either be considered as hadrons or not depending on the configuration.
*
*
* To allow performance studies following informations are tracked and returned:
* \arg the GenParticles identified as b-hadrons
* \arg if the b-hadron originates from the top-b-quark
* \arg a matrix showing which jets contain particles from which b-hadron (remnant from original approach in TopAnalysis)
*
* @param[in] genJets the GenJetCollection to be searched
* @param[out] hadIndex vector of indices of found hadrons in hadMothers
* @param[out] hadMothers vector of all mothers at all levels of each found hadron
* @param[out] hadMothersIndices connection between each particle from hadMothers and its mothers
* @param[out] hadFlavour flavour of each found hadron
* @returns vector of jets being matched to each hadron by jet clustering algorithm
*/
std::vector<int> GenLevelBJetAnalyzer::findHadronJets ( const reco::GenJetCollection& genJets, std::vector<int> &hadIndex, std::vector<reco::GenParticle> &hadMothers, std::vector<std::vector<int> > &hadMothersIndices, std::vector<int> &hadFlavour )
{

    std::vector<int> result;
    std::vector<const reco::Candidate*> hadMothersCand;

    const unsigned int nJets = genJets.size();
    bool hadVsJet[100][400]= {{false}};				// Whether jet contains decay products of the hadron (max 100 hadrons, 250 jets foreseen)


    for ( size_t iJet = 0; iJet < nJets; ++iJet )  {
        const reco::GenJet* thisJet = & ( genJets[iJet] );
        std::vector<const reco::GenParticle*> particles = thisJet->getGenConstituents();

    // printf(" genJet: %d pt: %.4f\teta: %.4f\tphi: %.4f\n",(int)iJet,thisJet->pt(),thisJet->eta(),thisJet->phi());
        for ( unsigned int iParticle = 0; iParticle < particles.size(); ++iParticle ) {
            const reco::GenParticle* thisParticle = particles[iParticle];
            const reco::Candidate* hadron = 0;
            if ( thisParticle->status() >1 ) {
                continue;    // Excluding non-final state particles (e.g. bHadrons)
            }
            int hadronIndex = analyzeMothers ( thisParticle, &hadron, hadMothersCand, hadMothersIndices, 0, -1 );
            if ( hadron ) { // Putting hadron index to the list if it is not yet
                int hadListIndex=-1;
                for ( unsigned int hadNum=0; hadNum<hadIndex.size(); hadNum++ ) {
                    if ( hadIndex[hadNum]!=hadronIndex ) {
                        continue;
                    }
                    hadListIndex=hadNum;
                    break;
                }
                if ( hadListIndex<0 ) {
                    hadIndex.push_back ( hadronIndex );
                    hadListIndex=hadIndex.size();
                }
                hadVsJet[hadListIndex][iJet]=true;		// Setting current jet as containing decay products of the found hadron
            }
        }   // End of loop over jet consituents
    }   // End of loop over jets

    for ( int i=0; i< ( int ) hadMothersCand.size(); i++ ) {
        hadMothers.push_back ( ( *dynamic_cast<const reco::GenParticle*> ( hadMothersCand.at(i) ) ) );
    }

// Checking mothers of hadrons in order to assign flags (where the hadron comes from)
    unsigned int nHad = hadIndex.size();

// Checking number of different flavours of hadrons in the event
    int nFlavHadrons[5] = {0};		// Numbers of hadrons (0-Top, 1-Higgs, 2-Gluon, 3-Z)

    std::vector<std::vector<int> > LastQuarkMotherIds;
    std::vector<std::vector<int> > LastQuarkIds;
    std::vector<int> lastQuarkIndices(nHad, -1);

// Looping over all hadrons
    for ( unsigned int hadNum=0; hadNum<nHad; hadNum++ ) {

        unsigned int hadIdx = hadIndex.at(hadNum);   // Index of hadron in the hadMothers
        const reco::GenParticle* hadron = &hadMothers.at(hadIdx);
        int jetIndex = -1;

// Looping over all jets to match them to current hadron
        for ( unsigned int jetNum = 0; jetNum < nJets; jetNum++ ) {
// Checking whether jet contains this hadron in it (that was put in jet by clustering algorithm)
            std::vector<const reco::GenParticle*> particles = genJets.at(jetNum).getGenConstituents();
            for ( unsigned int partNum=0; partNum<particles.size(); partNum++ ) {
                const reco::GenParticle* particle = particles.at(partNum);
                if ( particle->status() <2 ) {
                    continue;    // Skipping final state particles
                }
                if ( !isHadron ( flavour_,particle ) ) {
                    continue;
                }
// Checking whether hadron and particle in jet are identical
                if ( hadron->pdgId() !=particle->pdgId() || fabs ( hadron->eta()-particle->eta() ) >0.00001 || fabs ( hadron->phi()-particle->phi() ) >0.00001 ) {
                    continue;
                }
                jetIndex=jetNum;
                break;
            }   // End of loop over jet constituents
            if ( jetIndex>=0 ) {
                break;
            }
        }   // End of loop over jets

        result.push_back ( jetIndex );  // Putting jet index to the result list

        std::vector <int> FirstQuarkId;
        std::vector <int> LastQuarkId;
        std::vector <int> LastQuarkMotherId;

        int hadFlav = hadMothers.at(hadIdx).pdgId() <0?-1:1; // Charge of the hadron (-1,1)
        if ( abs ( hadMothers.at(hadIdx).pdgId() ) /1000 < 1 ) {
            hadFlav*=-1;    // Inverting flavour of hadron if it is a meson
        }

        // Creating a list of pdgIds of neutral hadrons
        int bHadNeutralPdg_[] = {511, 513, 515, 531, 533, 535, 551, 553, 555, 5122, 5142, 5212,
          5214, 5232, 5322, 5324, 5342, 5412, 5414, 5432, 5434, 5522, 5524, 5542, 5544 };
        std::vector<int> bHadNeutralPdg (bHadNeutralPdg_, bHadNeutralPdg_ + sizeof(bHadNeutralPdg_) / sizeof(int) );
        bool verbose = false;

        // Checking whether this is a neutral hadron
        // if(std::find(bHadNeutralPdg.begin(), bHadNeutralPdg.end(), std::abs(hadMothers[hadIdx].pdgId()) ) != bHadNeutralPdg.end() ) {
        //   verbose = false;
        // }

        if(verbose) printf("\n\n\nChecking a hadron: %d ##########################################\n", hadMothers[hadIdx].pdgId());

// Searching only first quark in the chain with the same flavour as hadron
        findInMothers ( hadIdx, FirstQuarkId, hadMothersIndices, hadMothers, 0, hadFlav*flavour_, false, 1, verbose );
        if(verbose) {
          printf("Found %d b quarks Hadron: %d ###########################################\n", (int)FirstQuarkId.size(), hadMothers[hadIdx].pdgId());
          for(int i=0; i<(int)FirstQuarkId.size(); i++) {
            printf("   %d. pdgId: %d\tstatus: %d", i, hadMothers[FirstQuarkId[i]].pdgId(), hadMothers[FirstQuarkId[i]].status());
            // if(hadFlav*hadMothers[FirstQuarkId[i]].pdgId() < 0) printf(" WRONG CHARGE");
            printf("\n");
          }
        }
//      if((int)FirstQuarkId.size()<1) findInMothers ( hadIdx, FirstQuarkId, hadMothersIndices, hadMothers, 0, hadFlav*flavour_, true, 1, true );
        // if((int)FirstQuarkId.size()<1) printf(" NO QUARK FOUND!!!\n");
        // return result;


        // Filling histograms for each 1-st quark
        for ( unsigned int qId=0; qId<FirstQuarkId.size(); qId++ ) {
            int qFlav = ( hadMothers[FirstQuarkId[qId]].pdgId() <0 ) ?-1:1;
            if ( toPlot ) {
                h_firstQstatus->Fill ( hadMothers[FirstQuarkId[qId]].status() );
                h_firstQPdg->Fill ( hadMothers[FirstQuarkId[qId]].pdgId() );
                h2_firstQFlav_HadFlav->Fill ( hadFlav,qFlav );
            }

            // Getting mothers of the first quark
            std::vector<int> FirstQMotherId = hadMothersIndices.at ( FirstQuarkId[qId] );
            for ( unsigned int qmId=0; qmId<FirstQMotherId.size(); qmId++ ) {
                int qmFlav = ( hadMothers.at(FirstQMotherId.at(qmId)).pdgId() <0 ) ?-1:1;
                if ( toPlot ) {
                    h2_firstQFlav_QMotherFlav->Fill ( qFlav,qmFlav );
                }
            }		// End of loop over all mothers of the first quark of the hadron

            // Finding last quark of the hadron starting from the first quark
            // printf("   Looking for last b quark --------------------------------\n");
            findInMothers ( FirstQuarkId.at(qId), LastQuarkId, hadMothersIndices, hadMothers, 0, qFlav*flavour_, false, 2, verbose );

        }       // End of loop over all first quarks of the hadron
        // printf("   Found %d last b quarks +++++++++++++++++++++++++++++++\n", (int)LastQuarkId.size());
        // for(int i=0; i<(int)LastQuarkId.size(); i++) printf("      %d. qIdx: %d\tpdg: %d\tpt: %.3f\n", i, LastQuarkId.at(i), hadMothers.at(LastQuarkId.at(i)).pdgId(), hadMothers.at(LastQuarkId.at(i)).pt());

        // Setting initial flavour of the hadron
        int hadronFlavour = 0;

        std::vector<std::pair<double, int> > lastQuark_dR_id_pairs;

        // Finding the closest quark in dR
        for ( unsigned int qId=0; qId<LastQuarkId.size(); qId++ ) {
            int qIdx = LastQuarkId.at(qId);
            int qFlav = ( hadMothers.at ( qIdx ).pdgId() <0 ) ?-1:1;

            // Checking the dR between hadron and quark
            float dR = deltaR ( hadMothers[hadIdx].eta(),hadMothers[hadIdx].phi(),hadMothers[qIdx].eta(),hadMothers[qIdx].phi() );
            // printf("  qIdx: %d dR: %.3f\n", qIdx, dR);
            std::pair<double, int> dR_hadId_pair(dR,qIdx);
            lastQuark_dR_id_pairs.push_back(dR_hadId_pair);

            if ( toPlot ) {
                h_lastQstatus->Fill ( hadMothers.at ( qIdx ).status() );
                h_lastQPdg->Fill ( hadMothers.at ( qIdx ).pdgId() );
                h2_lastQFlav_HadFlav->Fill ( hadFlav,qFlav );
            }
        }       // End of loop over all last quarks of the hadron

        std::sort(lastQuark_dR_id_pairs.begin(), lastQuark_dR_id_pairs.end());

        for(unsigned int qId=0; qId<lastQuark_dR_id_pairs.size(); qId++) {
            int qIdx = lastQuark_dR_id_pairs.at(qId).second;
            // Putting id of the last quark to the vector
            LastQuarkId.at(qId) = qIdx;
            // Putting id of the mother of the last quark to the vector
            int qmIdx = hadMothersIndices.at ( qIdx ).at(0);
            LastQuarkMotherId.push_back( qmIdx );
            // Filling the plots
            int qFlav = ( hadMothers.at ( qIdx ).pdgId() <0 ) ?-1:1;
            int qmFlav = ( hadMothers.at ( LastQuarkMotherId.at ( qId ) ).pdgId() <0 ) ?-1:1;
            if ( toPlot ) {
                h2_lastQFlav_QMotherFlav->Fill ( qFlav,qmFlav );
                h2_lastQPdg_QMotherPdg->Fill ( hadMothers.at ( qIdx ).pdgId(),hadMothers.at ( LastQuarkMotherId.at ( qId ) ).pdgId() );
            }
        }

        if((int)LastQuarkId.size()>0) lastQuarkIndices.at(hadNum) = 0;     // Setting the first quark in array as a candidate if it exists

        LastQuarkIds.push_back( LastQuarkId );

        LastQuarkMotherIds.push_back ( LastQuarkMotherId );

        // if ( toPlot ) {
        //     h_lastQ_lastQ_dRmin->Fill ( dRmin );
        // }

        // printf("   Ordered last b quarks, hadron: %d +++++++++++++++++++\n", hadNum);
        // for(int i=0; i<(int)LastQuarkId.size(); i++) printf("      %d. qIdx: %d\tpdg: %d\tpt: %.3f\n", i, LastQuarkId.at(i), hadMothers.at(LastQuarkId.at(i)).pdgId(), hadMothers.at(LastQuarkId.at(i)).pt());
       
        if(lastQuarkIndices.at(hadNum)<0) {
            hadronFlavour = 0;
        } else {
            int qIdx = LastQuarkId.at( lastQuarkIndices.at( hadNum ) );
            int qFlav = ( hadMothers.at(qIdx).pdgId() < 0 ) ? -1 : 1;
            hadronFlavour = qFlav*std::abs( hadMothers.at( LastQuarkMotherId.at( lastQuarkIndices.at( hadNum ) ) ).pdgId() );
        }
        hadFlavour.push_back(hadronFlavour);    // Adding hadron flavour to the list of flavours
		// printf("  hadronFlavour: %d (%d)\n",hadronFlavour,hadFlav);

        if(lastQuarkIndices.at(hadNum)>=0) {
            std::set<int> checkedHadronIds;
            bool noAmbiguity = fixExtraSameFlavours(hadNum, hadIndex, hadMothers, hadMothersIndices, LastQuarkIds, LastQuarkMotherIds, lastQuarkIndices, hadFlavour, checkedHadronIds, 0);

            int qIdx = LastQuarkId.at( lastQuarkIndices.at( hadNum ) );
            int qFlav = ( hadMothers.at(qIdx).pdgId() < 0 ) ? -1 : 1;
            hadronFlavour = qFlav*std::abs( hadMothers.at( LastQuarkMotherId.at( lastQuarkIndices.at( hadNum ) ) ).pdgId() );
            if(!noAmbiguity) hadronFlavour = qFlav*21;      // Assigning the gluon as mother of ambiguous hadron
        }

        // printf("  hadronFlavour: %d (%d)\n",hadronFlavour,hadFlav);

        int jetIdx1 = result[hadNum];   // Index of jet from matching by jet clustering algorithm

        int jetIdx2 = -1;
        float maxPt = 0.0;
        float dR_min=999.9;
// Looping over jets containing decay products of hadron to find the highest Pt one
        for ( unsigned int jetNum=0; jetNum<nJets; jetNum++ ) {
            if ( toPlot ) {
                float dR = deltaR ( genJets[jetNum].eta(),genJets[jetNum].phi(),hadron->eta(),hadron->phi() );
                if ( dR<dR_min ) {
                    dR_min=dR;
                }
            }
            if ( !hadVsJet[hadNum][jetNum] ) {
                continue;
            }
            if ( genJets[jetNum].pt() <=maxPt ) {
                continue;
            }
            maxPt=genJets[jetNum].pt();
            jetIdx2=jetNum;
        }

        if ( toPlot ) {
            h_hadJetIndex->Fill ( jetIdx1 );
            h_hadJet_dRmin->Fill ( dR_min );
            if ( jetIdx1>=0 ) {
                h_jetHad_dR->Fill ( deltaR ( genJets[jetIdx1].eta(),genJets[jetIdx1].phi(),hadron->eta(),hadron->phi() ) );
            }
            if ( jetIdx2>=0 && jetIdx1>=0 ) {
                h_jetdPt->Fill ( genJets[jetIdx1].pt() /genJets[jetIdx2].pt() );
                h_jetDeltaPt->Fill ( genJets[jetIdx1].pt()-genJets[jetIdx2].pt() );
            }
            if ( jetIdx2>=0 ) {
                h_jetHadOld_dR->Fill ( deltaR ( genJets[jetIdx2].eta(),genJets[jetIdx2].phi(),hadron->eta(),hadron->phi() ) );
            }
// Setting index to highest Pt jet containing decay products of the hadron if no jet was associated by jet clustering algorithm
            if ( jetIdx2>=0 && jetIdx1<0 ) {
                h_jetHadOldNoMatch_dR->Fill ( deltaR ( genJets[jetIdx2].eta(),genJets[jetIdx2].phi(),hadron->eta(),hadron->phi() ) );
            }
            if ( jetIdx2>=0 && jetIdx1<0 && abs ( hadronFlavour ) ==0 ) {
                h_jetHadOldNoMatch_dR_noFlav->Fill ( deltaR ( genJets[jetIdx2].eta(),genJets[jetIdx2].phi(),hadron->eta(),hadron->phi() ) );
            }
            if ( abs ( hadronFlavour ) ==0 && jetIdx1>=0 ) {
                h_jetHad_dR_noFlav->Fill ( deltaR ( genJets[jetIdx1].eta(),genJets[jetIdx1].phi(),hadron->eta(),hadron->phi() ) );
            }

            h_nFirstQ->Fill ( FirstQuarkId.size() );
            h_nLastQ->Fill ( LastQuarkId.size() );
        }
    }		// End of loop over all hadrons


// Checking number of different flavours of hadrons in the event
    for ( unsigned int i=0; i<hadFlavour.size(); i++ ) {
        h_hadFlavour->Fill( hadFlavour.at(i) );
        // printf("HADRON %d : FLAVOUR %d\n", i, hadFlavour.at(i));
        switch ( abs ( hadFlavour.at ( i ) ) ) {
        case 6:
            nFlavHadrons[0]++;	// Top
            break;
        case 25:
            nFlavHadrons[1]++;	// Higgs
            break;
        case 21:
            nFlavHadrons[2]++;	// Gluon
            break;
        case 23:
            nFlavHadrons[3]++;	// Z
            break;
        default:
            nFlavHadrons[4]++;	// No
            break;
        }
    }

    // if( nFlavHadrons[0] > 3 ) printf("nHadTop > 3\n\n");
    // if( nFlavHadrons[1] < 2 ) printf("nHadHiggs < 2**********************\n\n");

    if ( toPlot ) {
        h_nHad->Fill ( nHad );
        h_nHadTop->Fill ( nFlavHadrons[0] );
        h_nHadHiggs->Fill ( nFlavHadrons[1] );
        h_nHadGluon->Fill ( nFlavHadrons[2] );
        h_nHadZ->Fill ( nFlavHadrons[3] );
        h_nHadNo->Fill ( nFlavHadrons[4] );

// Filling number of hadrons associated to a single jet
        for ( unsigned int iJet=0; iJet<nJets; iJet++ ) {
            int N = 0;
            for ( unsigned int i=0; i<result.size(); i++ ) if ( result[i]== ( int ) iJet ) {
                    N++;
                }
            h_nHadInJet->Fill ( N );
        }

    }		// If validation histograms should be filled

    return result;
}

/**
* @brief helper function to keep track of the decay chain and identify loops in the decay tree
*
* @param[out] particleChain vector of particles building up the current chain
* @param[in] particle particle that should be added
*
* returns true if a particle is already in the chain
*/
bool GenLevelBJetAnalyzer::checkForLoop ( std::vector<const reco::Candidate*> &particleChain, const reco::Candidate* particle )
{

    for ( unsigned int i = 0; i < particleChain.size(); ++i ) {
        if ( particleChain[i]->pdgId() == 91 || particleChain[i]->pdgId() == 92 ) {
            continue;    // Ignoring clusters and strings
        }
        if ( particleChain[i] ==  particle ) {
            return true;
        }
    }

    particleChain.push_back ( particle );
    return false;
}

/**
* @brief Check if the cpecified particle is already in the list of particles
*
* @param[in] particleList - list of particles to be checked
* @param[in] particle - particle that should be checked
*
* returns true if a particle is already in the list
*/
int GenLevelBJetAnalyzer::isInList ( std::vector<const reco::Candidate*> particleList, const reco::Candidate* particle )
{
    for ( unsigned int i = 0; i<particleList.size(); i++ )
        if ( particleList[i]==particle ) {
            return i;
        }

    return -1;
}


/**
* @brief Check the pdgId of a given particle if it is a hadron
*
* @param[in] flavour - flavour of a hadron that is being searched (5-B, 4-C)
* @param[in] thisParticle - a particle that is to be analysed
*
* @returns if the particle is a hadron of specified flavour
*/
bool GenLevelBJetAnalyzer::isHadron ( const int flavour, const reco::Candidate* thisParticle )
{
    return isHadronPdgId(flavour, thisParticle->pdgId());
}

/**
* @brief Check the pdgId if it represents a hadron of particular flavour
*
* @param[in] flavour - flavour of a hadron that is being searched (5-B, 4-C)
* @param[in] pdgId - pdgId to be checked
*
* @returns if the pdgId represents a hadron of specified flavour
*/
bool GenLevelBJetAnalyzer::isHadronPdgId ( const int flavour, const int pdgId )
{
    int flavour_abs = std::abs(flavour);
    int pdgId_abs = std::abs(pdgId);

    if ( pdgId_abs / 1000 == flavour_abs // baryons
            || ( pdgId_abs / 100 % 10 == flavour_abs // mesons
                 && ! ( noBBbarResonances_ && pdgId_abs / 10 % 100 == 11*flavour_abs ) // but not a resonance
               )
       ) {
        return true;
    } else {
        return false;
    }
}

/**
* @brief Check if the particle has bHadron among daughters
*
* @param[in] flavour - flavour of a hadron that is being searched (5-B, 4-C)
* @param[in] thisParticle - a particle that is to be analysed
*
* @returns if the particle has a hadron among its daughters
*/
bool GenLevelBJetAnalyzer::hasHadronDaughter ( const int flavour, const reco::Candidate* thisParticle )
{
// Looping through daughters of the particle
    bool hasDaughter = false;
    for ( int k=0; k< ( int ) thisParticle->numberOfDaughters(); k++ ) {
        if ( !isHadron ( flavour, thisParticle->daughter ( k ) ) ) {
            continue;
        }
        hasDaughter = true;
        break;
    }
    return hasDaughter;
}

/**
* @brief do a recursive search for the mother particles until the b-quark is found or the absolute mother is found
*
* the treatment of b-bar resonances depends on the global parameter noBBbarResonances_
*
* @param[in] thisParticle current particle from which starts the search of the hadron and all its mothers up to proton
* @param[out] hadron the last hadron in the decay chain (that decays weekly)
* @param[out] hadMothers list of all particles starting with hadron and ending with proton
* @param[out] hadMothersIndices list of i-vectors containing j-indices representing particles that are mothers of each i-particle from hadMothers
*
* @returns index of the hadron in the hadMothers list. -1 if no hadron found
*/
int GenLevelBJetAnalyzer::analyzeMothers ( const reco::Candidate* thisParticle, pCRC *hadron, std::vector<const reco::Candidate*> &hadMothers, std::vector<std::vector<int> > &hadMothersIndices, std::set<const reco::Candidate*> *analyzedParticles, const int prevPartIndex )
{

    int hadronIndex=-1;	// Index of the hadron that is returned by this function
// Storing the first hadron has been found in the chain when going up from the final particle of the jet
    if ( *hadron == 0 // find only the first b-hadron on the way (the one that decays weekly)
            && isHadron ( flavour_, thisParticle ) // is a hadron
            && !hasHadronDaughter ( flavour_, thisParticle ) // has no hadron daughter (decays weekly)
       ) {
        *hadron = thisParticle;

        int index = isInList ( hadMothers, thisParticle );

        if ( index<0 ) { // If hadron is not in the list of mothers yet
            hadMothers.push_back ( thisParticle );
            hadronIndex=hadMothers.size()-1;
        } else {	    // If hadron is in the list of mothers already
            hadronIndex=index;
        }
    }

    //################################################### FOR SHERPA
    // if(hadronIndex > -1) return hadronIndex;
    //################################################### FOR SHERPA

    int partIndex = -1;	  // Index of particle being checked in the list of mothers
    partIndex = isInList ( hadMothers, thisParticle );

// Checking whether this particle is already in the chain of analyzed particles in order to identify a loop
    bool isLoop = false;
    if ( !analyzedParticles ) {
        analyzedParticles = new std::set<const reco::Candidate*>;
    }
    for ( unsigned int i=0; i<analyzedParticles->size(); i++ ) {
        if ( analyzedParticles->count ( thisParticle ) <=0 ) {
            continue;
        }
        isLoop = true;
        break;
    }


// If a loop has been detected
    if ( isLoop ) {
        if ( prevPartIndex>=0 ) {
            putMotherIndex ( hadMothersIndices, prevPartIndex, -1 );    // Setting mother index of previous particle to -1
        }
        return hadronIndex;		// Stopping further processing of the current chain
    }
    analyzedParticles->insert ( thisParticle );


// Putting the mothers to the list of mothers
    for ( size_t iMother = 0; iMother < thisParticle->numberOfMothers(); ++iMother ) {
        const reco::Candidate* mother = thisParticle->mother ( iMother );
        int mothIndex = isInList ( hadMothers, mother );
        if ( mothIndex == partIndex && partIndex>=0 ) {
            continue;		// Skipping the mother that is its own daughter
        }

        int nSameDaugh=0;

// Checking whether this mother has other daughters that have the same pdgId [Only if plotting option is enabled]
        if ( toPlot && abs ( thisParticle->pdgId() ) ==flavour_ && abs ( thisParticle->pdgId() ) == abs ( mother->pdgId() ) ) {
            double highPt = -1.0;
            int highPtId = -1;
// Loop over daughters of the mother to look how many daughters with the same pdgId it has
            float dR_min=999.9;
            for ( unsigned int iDaughter = 0; iDaughter<mother->numberOfDaughters(); iDaughter++ ) {
                const reco::Candidate* daughter = mother->daughter ( iDaughter );
                if ( abs ( daughter->pdgId() ) !=abs ( thisParticle->pdgId() ) ) {
                    continue;
                }
                nSameDaugh++;
            }
            for ( unsigned int iDaughter = 0; iDaughter<mother->numberOfDaughters(); iDaughter++ ) {
                const reco::Candidate* daughter = mother->daughter ( iDaughter );
                if ( abs ( daughter->pdgId() ) !=abs ( thisParticle->pdgId() ) ) {
                    continue;
                }
                if ( daughter->pdgId() *mother->pdgId() < 0 ) {
                    continue;
                }
                if ( daughter->pt() >highPt ) {
                    highPt=daughter->pt();
                    highPtId=iDaughter;
                }
                float dR=deltaR ( daughter->eta(),daughter->phi(),mother->eta(),mother->phi() );

                h_QQMothEFrac->Fill ( daughter->energy() /mother->energy() );
                h_QQMothdR->Fill ( dR );
                if ( nSameDaugh>1 ) {
                    h_QQMothEFrac_ambig->Fill ( daughter->energy() /mother->energy() );
                    h_QQMothdR_ambig->Fill ( dR );
                }

                if ( dR<dR_min ) {
                    dR_min=dR;
                }
            }

            if ( highPt<0.0 ) {
                continue;
            }
            for ( unsigned int iDaughter = 0; iDaughter<mother->numberOfDaughters(); iDaughter++ ) {
                const reco::Candidate* daughter = mother->daughter ( iDaughter );
                if ( daughter->pdgId() *mother->pdgId() < 0 ) {
                    continue;    // Skipping particles with wrong charge
                }
                if ( ( int ) iDaughter==highPtId ) {
                    if ( toPlot ) {
                        h_QHQdR->Fill ( deltaR ( daughter->eta(),daughter->phi(),mother->eta(),mother->phi() ) );
                        if ( nSameDaugh>1 ) {
                            h_QHQdR_ambig->Fill ( deltaR ( daughter->eta(),daughter->phi(),mother->eta(),mother->phi() ) );
                        }
                    }
                    continue;		// Skipping the highest Pt particle
                }
                h_QHQPtFrac->Fill ( ( highPt-daughter->pt() ) /highPt );
                if ( nSameDaugh>1 ) {
                    h_QHQPtFrac_ambig->Fill ( ( highPt-daughter->pt() ) /highPt );
                }
            }
            h_QQMothdR_min->Fill ( dR_min );
            if ( nSameDaugh>1 ) {
                h_QQMothdR_min_ambig->Fill ( dR_min );
            }
            h2_QQMothSamePdg->Fill ( thisParticle->pdgId(),mother->pdgId() );
        }	// If both particle and mother are quarks and have same abs(pdgId)

// If this mother isn't yet in the list and hadron is in the list
        if ( mothIndex<0 && ( *hadron ) !=0 ) {
            hadMothers.push_back ( mother );
            mothIndex=hadMothers.size()-1;
        }
// If hadron has already been found in current chain and the mother isn't a duplicate of the particle being checked
        if ( ( *hadron ) !=0 && mothIndex!=partIndex && partIndex>=0 ) {
            putMotherIndex ( hadMothersIndices, partIndex, mothIndex );			// Putting the index of mother for current particle
        }
        int index = analyzeMothers ( mother, hadron, hadMothers, hadMothersIndices, analyzedParticles, partIndex );
        hadronIndex = index<0?hadronIndex:index;
    }			// End of loop over mothers

    analyzedParticles->erase ( thisParticle );		// Removing current particle from the current chain that is being analyzed

    if ( partIndex<0 ) {
        return hadronIndex;    // Safety check
    }

// Adding -1 to the list of mother indices for current particle if it has no mothers (for consistency between numbering of indices and mothers)
    if ( ( int ) thisParticle->numberOfMothers() <=0 && ( *hadron ) !=0 ) {
        putMotherIndex ( hadMothersIndices, partIndex, -1 );
    }


    return hadronIndex;

}

/**
* @brief puts mother index to the list of mothers of particle, if it isn't there already
*
* @param[in] hadMothersIndices vector of indices of mothers for each particle
* @param[in] partIndex index of the particle for which the mother index should be stored
* @param[in] mothIndex index of mother that should be stored for current particle
*
*/
bool GenLevelBJetAnalyzer::putMotherIndex ( std::vector<std::vector<int> > &hadMothersIndices, int partIndex, int mothIndex )
{
    // Putting vector of mothers indices for the given particle
    bool inList=false;
    if ( partIndex<0 ) {
        return false;
    }

    while ( ( int ) hadMothersIndices.size() <=partIndex ) { // If there is no list of mothers for current particle yet
        std::vector<int> mothersIndices;
        hadMothersIndices.push_back ( mothersIndices );
    }

    std::vector<int> *hadMotherIndices=&hadMothersIndices.at ( partIndex );
// Removing other mothers if particle must have no mothers
    if ( mothIndex==-1 ) {
        hadMotherIndices->clear();
    } else {
// Checking if current mother is already in the list of theParticle's mothers
        for ( int k=0; k< ( int ) hadMotherIndices->size(); k++ ) {
            if ( hadMotherIndices->at ( k ) !=mothIndex && hadMotherIndices->at ( k ) !=-1 ) {
                continue;
            }
            inList=true;
            break;
        }
    }
// Adding current mother to the list of mothers of this particle
    if ( !inList ) {
        hadMotherIndices->push_back ( mothIndex );
    }

    return inList;
}


/**
* @brief helper function to resolve realname of PDG-ID
*/
std::string GenLevelBJetAnalyzer::getParticleName ( int id ) const
{

    const ParticleData * pd = 0;
    if ( resolveName_ ) {
        pdt_->particle ( id );
    }
    if ( !pd ) {
        std::ostringstream ss;
        ss << "P" << id;
        return ss.str();
    } else {
        return pd->name();
    }

}


/**
* @brief helper function to print jet properies
*
* this function is inlined to allow efficient optimisation when compiled without debug option
*
* @param[in] iJet the index of the jet
* @param[in] thisJet pointer to the jet
*
* @returns string to be printed
*/
inline std::string GenLevelBJetAnalyzer::printJetInfo ( const size_t iJet, const reco::GenJet* thisJet ) const
{
    std::ostringstream out;
    out <<  "Jet: " << iJet
        << " particles: " << thisJet->getGenConstituents().size()
        << " p4: " << thisJet->p4()
        << " p_t: " << thisJet->pt()
        << std::endl;
    return out.str();
}

/**
* @brief helper function to generate a human readable representation of the decay chain
*
* this function is inlined to allow efficient optimisation when compiled without debug option
*
* @param[in] particleChain the decay chain
* @param[in] hadron the identified b-hadron
*
* @returns string to be printed
*/
inline std::string GenLevelBJetAnalyzer::printParticleChain ( const std::vector<const reco::Candidate*> &particleChain, const reco::Candidate* hadron ) const
{
    std::ostringstream out;

    for ( int i = particleChain.size()-1; i >= 0; --i ) {
        if ( particleChain[i] == hadron ) {
            out << "*" << getParticleName ( particleChain[i]->pdgId() ) <<"*";
        } else {
            out << getParticleName ( particleChain[i]->pdgId() );
        }
        if ( i>0 ) {
            out  << "-->";
        }
    }
    return out.str();
}


/**
* @brief identify which of the jets is the nearest to the particle
*
* @param particle reference particle
* @param genJets candidate jets
* @returns index of the best jet in the vector or -1 if no jet within the maximum @f$\delta_{r}@f$
*/
int GenLevelBJetAnalyzer::getGenJetNear ( const reco::Candidate* particle, std::vector<const reco::GenJet*> &genJets )
{
    int result = -1;
    double bestDr = deltaR_;
    for ( unsigned int i = 0; i < genJets.size(); ++i ) {
        double dr = deltaR ( genJets[i]->eta(), genJets[i]->phi(), particle->eta(), particle->phi() );
        if ( dr < bestDr ) {
            bestDr = dr;
            result = i;
        }
    }
    return result;
}


/**
* @brief helper function to find indices of particles with particular pdgId and status from the list of mothers of a given particle
*
* @param[in] idx index of particle, mothers of which should be searched
* @param[in] hadMothersIndices list of indices pointing to mothers of each particle from list of mothers
* @param[in] hadMothers vector of all hadron mother particles of all levels
* @param[in] status status of mother that is being looked for
* @param[in] pdgId pdgId of mother that is being looked for
* @param[in] pdgAbs option, whether the sign of pdgId matters
* @param[in] charge charge of the particle (0 = any charge)
* @param[in] firstLast should all(0), first(1) or last(2) occurances of the searched particle be stored
* @param[in] verbose option to print every particle that is processed during the search
* @param[out] mothChains vector of indices where the found mothers are put
*
*/

void GenLevelBJetAnalyzer::findInMothers ( int idx, std::vector<int> &mothChains, std::vector<std::vector<int> > &hadMothersIndices, std::vector<reco::GenParticle> &hadMothers, int status, int pdgId, bool pdgAbs=false, int firstLast=0, bool verbose=false	)
{
    int pdg_1 = hadMothers.at ( idx ).pdgId();
    int partCharge = ( hadMothers.at ( idx ).pdgId() >0 ) ?1:-1;
// Inverting charge if mother is a b(c) meson
    if ( abs ( hadMothers.at ( idx ).pdgId() ) /1000 < 1 && ( abs ( hadMothers.at ( idx ).pdgId() ) /100%10 == 4 || abs ( hadMothers.at ( idx ).pdgId() ) /100%10 == 5 ) ) {
        partCharge*=-1;
    }

    if ( ( int ) hadMothersIndices.size() <=idx ) {
        if ( verbose ) {
            printf ( " Stopping checking particle %d. No mothers are stored.\n",idx );
        }
        return;	  // Skipping if no mothers are stored for this particle
    }

    std::vector<int> mothers = hadMothersIndices.at ( idx );
    unsigned int nMothers = mothers.size();
    bool isCorrect=false;		// Whether current particle is what is being searched
    if ( verbose ) {
        if ( abs ( hadMothers.at ( idx ).pdgId() ) ==2212 ) {
            printf ( "Chk:  %d\tpdg: %d\tstatus: %d",idx, hadMothers.at ( idx ).pdgId(), hadMothers.at ( idx ).status() );
        } else {
            printf ( " Chk:  %d(%d mothers)\tpdg: %d\tstatus: %d\tPt: %.3f\tEta: %.3f",idx, nMothers, hadMothers.at ( idx ).pdgId(), hadMothers.at ( idx ).status(), hadMothers.at ( idx ).pt(),hadMothers.at ( idx ).eta() );
        }
    }
    bool hasCorrectMothers = true;
    if(nMothers<1) hasCorrectMothers=false; else if(mothers.at(0)<0) hasCorrectMothers=false;
    // for ( unsigned int i=0; i<nMothers; i++ ) {
    //     int motherId = mothers.at ( i );
    //     if ( motherId<0 ) {
    //         continue;
    //     }
    //     if ( !isNeutralPdg ( hadMothers.at ( motherId ).pdgId() ) && hadMothers.at ( motherId ).pdgId() * hadMothers.at ( idx ).pdgId() < 0 && !pdgAbs && !isHadronPdgId(pdgId, hadMothers.at( motherId ).pdgId() ) ) {
    //         continue;    // Skipping if mother of the particle has wrong charge
    //     }
    //     hasCorrectMothers=true;
    //     break;
    // }
    if(!hasCorrectMothers) {
        if(verbose) printf("    NO CORRECT MOTHER\n");
        return;
    }
// Checking whether current mother satisfies selection criteria
    if ( ( ( hadMothers.at ( idx ).pdgId() == pdgId && pdgAbs==false )
            || ( abs ( hadMothers.at ( idx ).pdgId() ) == abs ( pdgId ) && pdgAbs==true ) )
            && ( hadMothers.at ( idx ).status() == status || status==0 )
            && hasCorrectMothers ) {
        isCorrect=true;
        bool inList=false;
        for ( unsigned int k=0; k<mothChains.size(); k++ ) if ( mothChains[k]==idx ) {
                inList=true;    // Checking whether isn't already in the list
                break;
            }
        if ( !inList && mothers.at ( 0 ) >=0 && ( hadMothers.at ( idx ).pdgId() *pdgId>0 || !pdgAbs ) ) {		// If not in list and mother of this quark has correct charge
            if ( firstLast==0 || firstLast==1 ) {
                mothChains.push_back ( idx );
            }
            if ( verbose ) {
                printf ( "   *" );
            }
        }
        if ( verbose ) {
            printf ( "   +++" );
        }
    }
    if ( verbose ) {
        printf ( "\n" );
    }

    if ( isCorrect && firstLast==1 ) {
        return;   // Stopping if only the first particle in the chain is looked for
    }

// Checking next level mothers
    for ( unsigned int i=0; i<nMothers; i++ ) {
        int idx2 = mothers[i];
        if ( idx2<0 ) {
            continue;    // Skipping if mother's id is -1 (no mother), that means current particle is a proton
        }
        if ( idx2==idx ) {
            continue;    // Skipping if particle is stored as its own mother
        }
        int pdg_2 = hadMothers[idx2].pdgId();
        // Inverting the flavour if bb oscillation identified
        if ( isHadronPdgId(pdgId, pdg_1) && isHadronPdgId(pdgId, pdg_2) &&  pdg_1*pdg_2 < 0 ) {
            pdgId*=-1;
            if(verbose) printf("######### Inverting flavour of the hadron\n");
        }
        if ( firstLast==2 && isCorrect && (
                    ( abs ( hadMothers[idx2].pdgId() ) != abs ( pdgId ) && pdgAbs==true ) ||
                    ( hadMothers[idx2].pdgId() != pdgId && pdgAbs==false ) ) ) {		// If only last occurance must be stored and mother has different flavour
            if ( verbose ) {
                printf ( "Checking mother %d out of %d mothers once more to store it as the last quark\n",i,nMothers );
            }
            findInMothers ( idx, mothChains, hadMothersIndices, hadMothers, 0, pdgId, pdgAbs, 1, verbose );
        }

// Checking next level mother
        if ( verbose ) {
            printf ( "Checking mother %d out of %d mothers with pdgId: %d\n",i,nMothers,pdgId );
        }
        findInMothers ( idx2, mothChains, hadMothersIndices, hadMothers, status, pdgId, pdgAbs, firstLast, verbose );
    }
}


/**
* @brief Check whether a given pdgId represents neutral particle
*
* @param[in] pdgId
* @param[in] thisParticle - a particle that is to be analysed
*
* @returns if the particle has a hadron among its daughters
*/
bool GenLevelBJetAnalyzer::isNeutralPdg ( int pdgId )
{
    const int max = 5;
    int neutralPdgs[max]= {9,21,22,23,25};
    for ( int i=0; i<max; i++ ) if ( abs ( pdgId ) ==neutralPdgs[i] ) {
            return true;
        }
    return false;
}


/**
 * Finds hadrons that have the same flavour and origin and resolve this ambiguity
 * @method fixExtraSameFlavours
 * @param  hadId                Index of the hadron being checked
 * @param  hadIndex             Vector of indices of each hadron pointing to the hadMothers
 * @param  hadMothers           Vector of gen particles (contain hadrons and all its ancestors)
 * @param  hadMothersIndices    Vector of indices for each particle from hadMothers
 * @param  LastQuarkIds         Vector of indices of last quarks for each hadron
 * @param  LastQuarkMotherIds   Vector of indices of mothers for each last quark from LastQuarkIds
 * @param  lastQuakIndices      Vector of indices pointing to particular index from the LastQuarkIds and LastQuarkMotherIds to be used for each hadron
 * @param  lastQuarkIndex       Index from the LastQuarkIds and LastQuarkMotherIds for this particular hadron with index hadId
 * @return Whether other mother with unique association has been found for the hadrons
 */
bool GenLevelBJetAnalyzer::fixExtraSameFlavours(
    const unsigned int hadId, const std::vector<int> &hadIndices, const std::vector<reco::GenParticle> &hadMothers, 
    const std::vector<std::vector<int> > &hadMothersIndices, const std::vector<std::vector<int> > &LastQuarkIds, 
    const std::vector<std::vector<int> > &LastQuarkMotherIds, std::vector<int> &lastQuarkIndices, std::vector<int> &hadronFlavour, 
    std::set<int> &checkedHadronIds, const int lastQuarkIndex)
{
    if(checkedHadronIds.count(hadId) != 0) return false;      // Hadron already checked previously and should be skipped
    checkedHadronIds.insert(hadId);                           // Putting hadron to the list of checked ones in this run

    if(lastQuarkIndex<0) return false;
    if((int)LastQuarkIds.at(hadId).size()<lastQuarkIndex+1) return false;
    int hadIndex = hadIndices.at(hadId);
    int LastQuarkId = LastQuarkIds.at(hadId).at(lastQuarkIndex);
    int LastQuarkMotherId = LastQuarkMotherIds.at( hadId ).at( lastQuarkIndex );
    int qmFlav = hadMothers.at(LastQuarkId).pdgId() < 0 ? -1 : 1;
    int hadFlavour = qmFlav*std::abs( hadMothers.at( LastQuarkMotherId ).pdgId() );
    bool ambiguityResolved = true;
    // If last quark has inconsistent flavour with its mother, setting the hadron flavour to gluon
    if(hadMothers.at(LastQuarkId).pdgId()*hadMothers.at(LastQuarkMotherId).pdgId() < 0 && !isNeutralPdg(hadMothers.at(LastQuarkMotherId).pdgId())) {
        hadronFlavour.at(hadId) = qmFlav*21;
        // printf("Setting flavour of hadron %d to %d (wrong mother flavour)\n", hadId, hadronFlavour.at(hadId));
        return true;
    }

    // printf("hadId: %d  LastQuarkId: %d hadFlavour: %d\n", hadId, LastQuarkId, hadFlavour);
    int nSameFlavourHadrons = 0;
    // Looping over all previous hadrons
    for(unsigned int iHad = 0; iHad<hadronFlavour.size(); iHad++) {
        if(iHad==hadId) continue;
        int theHadIndex = hadIndices.at(iHad);
        int theLastQuarkIndex = lastQuarkIndices.at(iHad);
        if(theLastQuarkIndex<0) continue;
        int theLastQuarkId = LastQuarkIds.at(iHad).at(theLastQuarkIndex);
        if((int)LastQuarkMotherIds.at( iHad ).size() <= theLastQuarkIndex) continue;
        int theLastQuarkMotherId = LastQuarkMotherIds.at( iHad ).at( theLastQuarkIndex );
        int theHadFlavour = hadronFlavour.at(iHad);
        // Skipping hadrons with different flavour
        if(theHadFlavour==0 || theHadFlavour==21) continue;
        // printf(" hadId: %d flavour: %d|%d motherId: %d(%.3f)|%d(%.3f)\n", iHad, hadFlavour, theHadFlavour, LastQuarkMotherId, hadMothers.at(LastQuarkMotherId).pt(), theLastQuarkMotherId, hadMothers.at(theLastQuarkMotherId).pt());
        if(theHadFlavour != hadFlavour || theLastQuarkMotherId != LastQuarkMotherId) continue;
        ambiguityResolved = false;
        nSameFlavourHadrons++;
        // printf("   hadId: %d  LastQuarkId: %d hadFlavour: %d\n", iHad, theLastQuarkId, theHadFlavour);
        
        // Checking other b-quark mother candidates of this hadron
        if((int)LastQuarkIds.at(hadId).size() > lastQuarkIndex+1) {
            if(fixExtraSameFlavours(hadId, hadIndices, hadMothers, hadMothersIndices, LastQuarkIds, LastQuarkMotherIds, lastQuarkIndices, hadronFlavour, checkedHadronIds, lastQuarkIndex+1) ) {
                ambiguityResolved = true;
                break;
            }
        } else
        // Checking other b-quark mother candidates of the particular previous hadron
        if((int)LastQuarkIds.at(iHad).size() > theLastQuarkIndex+1) {
            if(fixExtraSameFlavours(iHad, hadIndices, hadMothers, hadMothersIndices, LastQuarkIds, LastQuarkMotherIds, lastQuarkIndices, hadronFlavour, checkedHadronIds, theLastQuarkIndex+1) ) {
                ambiguityResolved = true;
                break;
            };
        } 

    }       // End of loop over all previous hadrons
    checkedHadronIds.erase(hadId);      // Removing the hadron from the list of checked hadrons
    if(nSameFlavourHadrons>0 && !ambiguityResolved) {
        hadronFlavour.at(hadId) = qmFlav*21;
        // printf("   Setting flavour of hadron %d to %d\n", hadId, hadronFlavour.at(hadId));

        return true;
    }
    lastQuarkIndices.at(hadId) = lastQuarkIndex;
    hadronFlavour.at(hadId) = hadFlavour;
    // printf("   Setting flavour of hadron %d to %d\n", hadId, hadronFlavour.at(hadId));
    return true;
}


//define this as a plug-in
DEFINE_FWK_MODULE ( GenLevelBJetAnalyzer );
