from TopAnalysis.Configuration.defines import sizes 
from TopAnalysis.Configuration.defines import source

######################################################################
#                                                                     
# -----------                                                         
#                                                                     
#                                                                     
# Events      :  11377412                                             
# xsec(pb)  LO:                                                       
# xsec(pb) NLO:                                                       
# eff         :                                                       
######################################################################
sizes ['wjets09_pat7_0'] = 240396
source['wjets09_pat7_0'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_1.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_10.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_100.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_101.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_102.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_103.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_104.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_105.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_106.root\','
source['wjets09_pat7_0']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_107.root\''

sizes ['wjets09_pat7_1'] = 250000
source['wjets09_pat7_1'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_108.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_109.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_11.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_110.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_111.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_112.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_113.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_114.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_115.root\','
source['wjets09_pat7_1']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_116.root\''

sizes ['wjets09_pat7_2'] = 250000
source['wjets09_pat7_2'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_117.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_118.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_119.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_12.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_120.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_121.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_122.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_123.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_124.root\','
source['wjets09_pat7_2']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_125.root\''

sizes ['wjets09_pat7_3'] = 250000
source['wjets09_pat7_3'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_126.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_127.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_128.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_129.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_13.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_130.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_131.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_132.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_133.root\','
source['wjets09_pat7_3']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_134.root\''

sizes ['wjets09_pat7_4'] = 250000
source['wjets09_pat7_4'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_135.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_136.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_137.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_138.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_139.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_14.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_140.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_141.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_142.root\','
source['wjets09_pat7_4']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_143.root\''

sizes ['wjets09_pat7_5'] = 250000
source['wjets09_pat7_5'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_144.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_145.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_146.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_147.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_148.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_149.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_15.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_150.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_151.root\','
source['wjets09_pat7_5']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_152.root\''

sizes ['wjets09_pat7_6'] = 250000
source['wjets09_pat7_6'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_153.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_154.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_155.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_156.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_157.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_158.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_159.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_16.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_160.root\','
source['wjets09_pat7_6']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_161.root\''

sizes ['wjets09_pat7_7'] = 250000
source['wjets09_pat7_7'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_162.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_163.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_164.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_165.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_166.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_167.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_168.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_169.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_17.root\','
source['wjets09_pat7_7']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_170.root\''

sizes ['wjets09_pat7_8'] = 250000
source['wjets09_pat7_8'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_171.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_172.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_173.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_174.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_175.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_176.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_177.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_178.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_179.root\','
source['wjets09_pat7_8']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_18.root\''

sizes ['wjets09_pat7_9'] = 250000
source['wjets09_pat7_9'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_180.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_181.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_182.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_183.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_184.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_185.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_186.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_187.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_188.root\','
source['wjets09_pat7_9']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_189.root\''

sizes ['wjets09_pat7_10'] = 242034
source['wjets09_pat7_10'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_19.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_190.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_191.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_192.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_193.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_194.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_195.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_196.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_197.root\','
source['wjets09_pat7_10']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_198.root\''

sizes ['wjets09_pat7_11'] = 250000
source['wjets09_pat7_11'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_199.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_2.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_20.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_200.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_201.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_202.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_203.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_204.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_205.root\','
source['wjets09_pat7_11']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_206.root\''

sizes ['wjets09_pat7_12'] = 250000
source['wjets09_pat7_12'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_207.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_208.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_209.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_21.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_210.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_211.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_212.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_213.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_214.root\','
source['wjets09_pat7_12']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_215.root\''

sizes ['wjets09_pat7_13'] = 250000
source['wjets09_pat7_13'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_216.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_217.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_218.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_219.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_22.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_220.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_221.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_222.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_223.root\','
source['wjets09_pat7_13']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_224.root\''

sizes ['wjets09_pat7_14'] = 250000
source['wjets09_pat7_14'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_225.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_226.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_227.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_228.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_229.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_23.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_230.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_231.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_232.root\','
source['wjets09_pat7_14']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_233.root\''

sizes ['wjets09_pat7_15'] = 250000
source['wjets09_pat7_15'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_234.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_235.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_236.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_237.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_238.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_239.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_24.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_240.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_241.root\','
source['wjets09_pat7_15']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_242.root\''

sizes ['wjets09_pat7_16'] = 250000
source['wjets09_pat7_16'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_243.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_244.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_245.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_246.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_247.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_248.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_249.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_25.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_250.root\','
source['wjets09_pat7_16']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_251.root\''

sizes ['wjets09_pat7_17'] = 250000
source['wjets09_pat7_17'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_252.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_253.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_254.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_255.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_256.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_257.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_258.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_259.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_26.root\','
source['wjets09_pat7_17']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_260.root\''

sizes ['wjets09_pat7_18'] = 250000
source['wjets09_pat7_18'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_261.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_262.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_263.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_264.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_265.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_266.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_267.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_268.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_269.root\','
source['wjets09_pat7_18']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_27.root\''

sizes ['wjets09_pat7_19'] = 250000
source['wjets09_pat7_19'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_270.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_271.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_272.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_273.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_274.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_275.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_276.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_277.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_278.root\','
source['wjets09_pat7_19']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_279.root\''

sizes ['wjets09_pat7_20'] = 239123
source['wjets09_pat7_20'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_28.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_280.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_281.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_282.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_283.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_284.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_285.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_286.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_287.root\','
source['wjets09_pat7_20']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_288.root\''

sizes ['wjets09_pat7_21'] = 250000
source['wjets09_pat7_21'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_289.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_29.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_290.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_291.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_292.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_293.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_294.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_295.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_296.root\','
source['wjets09_pat7_21']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_297.root\''

sizes ['wjets09_pat7_22'] = 250000
source['wjets09_pat7_22'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_298.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_299.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_3.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_30.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_300.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_301.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_302.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_303.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_304.root\','
source['wjets09_pat7_22']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_305.root\''

sizes ['wjets09_pat7_23'] = 250000
source['wjets09_pat7_23'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_306.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_307.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_308.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_309.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_31.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_310.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_311.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_312.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_313.root\','
source['wjets09_pat7_23']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_314.root\''

sizes ['wjets09_pat7_24'] = 250000
source['wjets09_pat7_24'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_315.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_316.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_317.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_318.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_319.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_32.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_320.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_321.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_322.root\','
source['wjets09_pat7_24']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_323.root\''

sizes ['wjets09_pat7_25'] = 250000
source['wjets09_pat7_25'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_324.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_325.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_326.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_327.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_328.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_329.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_33.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_330.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_331.root\','
source['wjets09_pat7_25']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_332.root\''

sizes ['wjets09_pat7_26'] = 250000
source['wjets09_pat7_26'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_333.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_334.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_335.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_336.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_337.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_338.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_339.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_34.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_340.root\','
source['wjets09_pat7_26']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_341.root\''

sizes ['wjets09_pat7_27'] = 250000
source['wjets09_pat7_27'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_342.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_343.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_344.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_345.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_346.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_347.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_348.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_349.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_35.root\','
source['wjets09_pat7_27']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_350.root\''

sizes ['wjets09_pat7_28'] = 250000
source['wjets09_pat7_28'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_351.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_352.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_353.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_354.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_355.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_356.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_357.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_358.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_359.root\','
source['wjets09_pat7_28']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_36.root\''

sizes ['wjets09_pat7_29'] = 250000
source['wjets09_pat7_29'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_360.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_361.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_362.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_363.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_364.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_365.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_366.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_367.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_368.root\','
source['wjets09_pat7_29']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_369.root\''

sizes ['wjets09_pat7_30'] = 250000
source['wjets09_pat7_30'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_37.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_370.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_371.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_372.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_373.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_374.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_375.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_376.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_377.root\','
source['wjets09_pat7_30']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_378.root\''

sizes ['wjets09_pat7_31'] = 250000
source['wjets09_pat7_31'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_379.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_38.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_380.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_381.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_382.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_383.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_384.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_385.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_386.root\','
source['wjets09_pat7_31']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_387.root\''

sizes ['wjets09_pat7_32'] = 250000
source['wjets09_pat7_32'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_388.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_389.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_39.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_390.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_391.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_392.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_393.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_394.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_395.root\','
source['wjets09_pat7_32']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_396.root\''

sizes ['wjets09_pat7_33'] = 229249
source['wjets09_pat7_33'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_397.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_398.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_399.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_4.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_40.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_400.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_401.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_402.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_403.root\','
source['wjets09_pat7_33']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_404.root\''

sizes ['wjets09_pat7_34'] = 250000
source['wjets09_pat7_34'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_405.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_406.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_407.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_408.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_409.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_41.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_410.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_411.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_412.root\','
source['wjets09_pat7_34']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_413.root\''

sizes ['wjets09_pat7_35'] = 250000
source['wjets09_pat7_35'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_414.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_415.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_416.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_417.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_418.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_419.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_42.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_420.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_421.root\','
source['wjets09_pat7_35']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_422.root\''

sizes ['wjets09_pat7_36'] = 250000
source['wjets09_pat7_36'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_423.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_424.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_425.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_426.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_427.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_428.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_429.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_43.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_430.root\','
source['wjets09_pat7_36']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_431.root\''

sizes ['wjets09_pat7_37'] = 250000
source['wjets09_pat7_37'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_432.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_433.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_434.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_435.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_436.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_437.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_438.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_439.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_44.root\','
source['wjets09_pat7_37']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_440.root\''

sizes ['wjets09_pat7_38'] = 250000
source['wjets09_pat7_38'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_441.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_442.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_443.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_444.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_445.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_446.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_447.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_448.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_449.root\','
source['wjets09_pat7_38']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_45.root\''

sizes ['wjets09_pat7_39'] = 226610
source['wjets09_pat7_39'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_450.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_451.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_452.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_453.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_454.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_455.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_456.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_457.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_458.root\','
source['wjets09_pat7_39']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_46.root\''

sizes ['wjets09_pat7_40'] = 250000
source['wjets09_pat7_40'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_47.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_48.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_49.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_5.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_50.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_51.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_52.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_53.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_54.root\','
source['wjets09_pat7_40']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_55.root\''

sizes ['wjets09_pat7_41'] = 250000
source['wjets09_pat7_41'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_56.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_57.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_58.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_59.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_6.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_60.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_61.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_62.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_63.root\','
source['wjets09_pat7_41']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_64.root\''

sizes ['wjets09_pat7_42'] = 250000
source['wjets09_pat7_42'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_65.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_66.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_67.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_68.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_69.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_7.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_70.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_71.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_72.root\','
source['wjets09_pat7_42']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_73.root\''

sizes ['wjets09_pat7_43'] = 250000
source['wjets09_pat7_43'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_74.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_75.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_76.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_77.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_78.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_79.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_8.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_80.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_81.root\','
source['wjets09_pat7_43']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_82.root\''

sizes ['wjets09_pat7_44'] = 250000
source['wjets09_pat7_44'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_83.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_84.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_85.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_86.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_87.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_88.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_89.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_9.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_90.root\','
source['wjets09_pat7_44']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_91.root\''

sizes ['wjets09_pat7_45'] = 200000
source['wjets09_pat7_45'] ='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_92.root\','
source['wjets09_pat7_45']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_93.root\','
source['wjets09_pat7_45']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_94.root\','
source['wjets09_pat7_45']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_95.root\','
source['wjets09_pat7_45']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_96.root\','
source['wjets09_pat7_45']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_97.root\','
source['wjets09_pat7_45']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_98.root\','
source['wjets09_pat7_45']+='\'/store/user/henderle/samples/Wjets_madgraph_7TeV/PATtuple_99.root\''

